[BE] 슬랙 알림 기능을 구현한다.
woowacourse-teams/2022-gong-check pull request #127
Opened 2022-07-14 11:24 UTC by meatsby

## issue
- resolve #117 

## 코드 설명
- 슬랙이 제공하는 의존성이 추가됨
- 이제 `submitJobCompletion()` 이 `SubmissionResponse` 를 반환
- 슬랙 메시지를 전송하는 `SlackService` 가 추가됨
- 슬랙이 제공하는 JSON 형식에 맞춘 `Attatchments` 클래스가 추가됨
- 인수테스트 최상위 클래스에 `@MockBean` 이 추가됨
- `Job` 엔티티에 `slackUrl` 필드가 추가됨

### 의논거리
- `RANDOM_PORT` 사용 시 `SlackService` 를 의존하는 `Controller` 에서만 `@MockBean` 을 사용할 수 있음

2022-07-14 12:07 UTC, jinyoungchoi95 requested changes
고생하셨습니다 :)

2022-07-14 12:07 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/presentation/SubmissionController.java
> +        slackService.sendMessage(submissionResponse);
slack 요청이 실패되었을 때는 예외가 발생해서 bad request가 날아갈텐데 `submissionService`에서는 이미 저장되어서 bad request라는 상황이 애매해질 수 있다라고 생각해요.

slack이라는 외부서비스에서 어떤 문제가 발생하는지 판단하기 힘들다면 `sendMessage`를 비동기처리해두고 ok를 바로 보내는 방법도 있고, slack이 우리 서비스에서 중요한 알람이라고본다면 `submitJobCompletion` 트랜잭션안에 두고 slack에 알람이 가짇않아 수락자체가 실패도록 하는 방향도 생각할 수 있을 것 같아요.

2022-07-14 15:12 UTC, cndqjacndqja approved these changes
고생하셨습니다 🤗

2022-07-14 15:12 UTC, cndqjacndqja commented on backend/src/main/java/com/woowacourse/gongcheck/application/SlackAPIService.java
> +public class SlackAPIService implements SlackService {
혹시 `@Transactional`을 사용한 이유가 궁금합니다! :)

2022-07-15 07:26 UTC, awesomeo184 approved these changes
고생하셨어요. 의견 한가지 남겼어요~ 반영 안 하셔도 됩니다.

2022-07-15 07:47 UTC, kimchan123 approved these changes
고생하셨슴니다👍

2022-07-15 07:47 UTC, kimchan123 commented on backend/src/test/java/com/woowacourse/gongcheck/acceptance/AcceptanceTest.java
> +
안쓰고 있는 것 같은데 지워도 좋을 것 같아요!

2022-07-15 07:54 UTC, meatsby commented on backend/src/test/java/com/woowacourse/gongcheck/acceptance/AcceptanceTest.java
> +
MockBean 을 사용하지 않으면 실제로 메시지가 날아가서 MockBean 으로 아예 호출을 막으려는 의도였습니닷!

2022-07-15 07:55 UTC, meatsby commented on backend/src/main/java/com/woowacourse/gongcheck/application/SlackService.java
> +}
일리가 있네용 추후에 다른 알림 서비스를 적용하게 된다면 네이밍 변경을 고려해보겠습니다!

2022-07-15 07:55 UTC, meatsby commented on backend/src/main/java/com/woowacourse/gongcheck/application/SlackAPIService.java
> +public class SlackAPIService implements SlackService {
사실 필요 없을 것 같네요! 제거햇습니다!

2022-07-16 16:37 UTC, jinyoungchoi95 approved these changes
고생하셨습니다~

2022-07-16 16:37 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/application/AsyncConfig.java
> +public class AsyncConfig extends AsyncConfigurerSupport {
👍

2022-07-16 16:37 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/application/SlackService.java
> +    @Async
```suggestion
    @Async
    @Override
```
`@Override`는 어짜피 제거되어도 돌아간다라고 생각한다면 `@Async`가 먼저가 되면 좋을 것 같네요 :)

2022-07-16 16:37 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/presentation/SubmissionController.java
> +        }
추후 개선하는걸로!

2022-07-18 04:43 UTC, merged