[BE] Github Oauth 로그인 기능을 구현한다.
woowacourse-teams/2022-gong-check pull request #144
Opened 2022-07-15 09:32 UTC by kimchan123

## issue
- resolve #115 
- resolve #164 

## 코드 설명
- Github Oauth를 통해 로그인 기능을 구현하였습니다.
- Host entity에 github_id, image_url이 추가 되었습니다. 
    - (github_id : unique, not null & image_url : not null)
-> 그에 따른 테스트 코드 수정이 꽤 발생했습니다. 그렇게 복잡한 변화는 아니라 금방 파악할 수 있을 거에요!
- 로그인한 회원이 이미 존재하면 조회, 존재하지 않는 회원이면 생성합니다.
(생성 시 `Default SpacePassword`는 `0000`으로 설정하였습니다)
- host, guest별로 접근 가능한 api 판단을 위해 AuthenticationContext에 authority라는 추가적인 필드를 부여하였습니다. 

아래는 대략적인 OAuth 흐름입니다.

1. github에서 client_id, client_secret을 발급받는다.
2. https://github.com/login/oauth/authorize?client_id=${client_id} 를 통해 로그인에 성공하면 깃허브가 Authorization_code를 발급한다.
3. 클라이언트가 서버로 Authorization_code를 전달한다.
4. 서버는 github에게 client_id, client_secret, authorization_code를 전송한다.
5. github는 전달받은 데이터가 옳다면 서버측에 access_token을 발급한다.
6. 서버는 access_token을 통해 해당 사용자의 프로필을 요청한다.
7. github는 전달받은 토큰이 옳다면 서버측에 사용자의 프로필 정보를 반환한다.
8. 서버는 githubId를 통해 해당 유저가 존재하면 조회, 아니면 생성한다.
9. JwtTokenProvider를 사용해 해당 유저의 Id를 subject에 담아 토큰을 생성한다.
10. 토큰을 클라이언트에게 전달한다.

## 추가적으로 구현한 것
- git submodule을 이용해 중요 정보인 application-oauth.yml 파일을 숨겼습니다.
- 저희 gong-check organization의 private repository인 submodule에 해당 파일을 업로드 했습니다.
- 자세한 내용은 https://tecoble.techcourse.co.kr/post/2021-07-31-git-submodule/ 를 참고해주시면 감사하겠습니다!

2022-07-16 07:58 UTC, awesomeo184 approved these changes
찬 고생 많으셨어요, 잘 이해되지 않는 부분에 코멘트 달았어요~

2022-07-16 07:58 UTC, awesomeo184 commented on backend/src/main/java/com/woowacourse/gongcheck/application/response/TokenResponse.java
> +    private boolean existHost;
existHost가 응답으로 나가는 이유를 알 수 있을까요?

2022-07-16 07:58 UTC, awesomeo184 commented on backend/src/test/java/com/woowacourse/gongcheck/application/HostAuthServiceTest.java
> +    void code를_받아_token과_존재하지_않는_Host이면_false를_반환한다() {
메서드 명이 잘 이해가 가지 않아용

2022-07-16 16:27 UTC, kimchan123 commented on backend/src/main/java/com/woowacourse/gongcheck/application/response/TokenResponse.java
> +    private boolean existHost;
프론트측에서 existHost가 false이면 최초 회원가입하는 것 처럼 추가 정보 입력창으로 넘어가고 true이면 바로 로그인 처리를 해주려고 existHost 필드를 추가했어요! 월요일에 한번 얘기 나눠보면 좋을 것 같아요. 미리 말씀 못드려서 죄송합니다 ㅠㅠ

2022-07-16 16:30 UTC, kimchan123 commented on backend/src/test/java/com/woowacourse/gongcheck/application/HostAuthServiceTest.java
> +    void code를_받아_token과_존재하지_않는_Host이면_false를_반환한다() {
```java
@Nested
class code를_받아_token을_반환한다 {

    @Test
    void 존재하지_않는_Host이면_existHost가_false이다() {}
}
```
이렇게 바꿔보려고 하는데 괜찮을까요?

2022-07-17 08:26 UTC, jinyoungchoi95 requested changes
고생하셨습니다~

코멘트 확인 부탁드려요 :)

2022-07-17 08:26 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/application/GithubOauthClient.java
> +    private static final String AUTHORIZATION_HEADER = "Authorization";
`HttpHeaders.AUTHORIZATION`이라는 제공되는 상수값이 있는데 확인해주세요 :)

2022-07-17 08:26 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/application/GithubOauthClient.java
> +        if (accessToken == null) {
```suggestion
        if (Objects.isNull(accessToken)) {
```
최대한 제공되는 메소드를 사용함으로써 메소드 네이밍에 의미를 담아주는것이 중요합니다 :)

2022-07-17 08:26 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/application/HostAuthService.java
> +                           final HostRepository hostRepository) {
줄바꿈 너무 많이되어있는 것 같아요~

2022-07-17 08:26 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/application/response/GithubProfileResponse.java
> +    public static final String DEFAULT_SPACE_PASSWORD = "0000";
default한 password를 설정하는 것은 도메인단에서 이루어져야하는 행위가 아닐까요 ?.?

2022-07-17 08:26 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/application/JwtTokenProvider.java
> +    Authority extractAuthority(final String token);
이 메소드도 명시적으로는 `extractSubject`와 마찬가지로 `throws UnauthorizedException`을 걸어주세요 ~

2022-07-17 08:26 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/application/response/GithubProfileResponse.java
> +    public Host toHost() {
👍

2022-07-17 08:26 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/application/response/TokenResponse.java
> +    private boolean existHost;
조오금 불명확한 네이밍인 것 같아요
Host는 회원가입을 했으니 당연히 exist인데 `Host가 존재하는가`라는 네이밍은 얼핏 보았을때 무슨 의미지라는게 먼저 생각이 나는 것 같네요

조금 더 명확한 의미가 없을까요? 최초 가입 여부라는 의미를 조금 더 명확하게 할만한 걸루요 :)

2022-07-17 08:26 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/config/WebConfig.java
> +                .excludePathPatterns("/api/login");
login url을 보니 host와 guest의 url에 대한 구분이 조금 더 되어야겠다라는 생각이 더 들게되네요

2022-07-17 08:26 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/domain/host/Host.java
> +                final LocalDateTime createdAt,
불필요한 한줄 띄워져있네요

2022-07-17 08:26 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/domain/host/HostRepository.java
> +    boolean existsByGithubId(final Long githubId);
default 메소드를 모두 아래에 두는 것이 좋을 것 같아요~

2022-07-17 08:26 UTC, jinyoungchoi95 commented on backend/src/main/resources/application.yml
> +    include: test
이게 안걸리면 빌드가 터진다는 이야기였던거죠?

2022-07-17 14:12 UTC, kimchan123 commented on backend/src/main/resources/application.yml
> +    include: test
넵! 최초엔 includes: oauth로 설정했는데 해당 yml이 없어서 빌드가 실패했어요. submodule 적용해 해결해볼게요!

2022-07-18 01:08 UTC, kimchan123 commented on backend/src/main/java/com/woowacourse/gongcheck/application/GithubOauthClient.java
> +    private static final String AUTHORIZATION_HEADER = "Authorization";
Accept 헤더도 존재하길래 같이 변경했어요!

2022-07-18 04:54 UTC, kimchan123 commented on backend/src/main/java/com/woowacourse/gongcheck/application/GithubOauthClient.java
> +        if (accessToken == null) {
😀👍

2022-07-18 05:18 UTC, kimchan123 commented on backend/src/main/java/com/woowacourse/gongcheck/application/response/GithubProfileResponse.java
> +    public static final String DEFAULT_SPACE_PASSWORD = "0000";
도메인단에서 이루어져야 하는게 맞다고 이를 도메인에서 설정해주려면 @Builder를 클래스 단에 선언하고 @Builder.Default를 필드에 선언해줘야 하는데 지금 상태는 생성자에 @Builder가 선언되어 있는 상태입니다. 이를 클래스 단에 선언하는 방법은 어떨까요 ?

2022-07-18 05:21 UTC, kimchan123 commented on backend/src/main/java/com/woowacourse/gongcheck/application/response/TokenResponse.java
> +    private boolean existHost;
firstLogin 이라는 명은 어떨까요 ?

2022-07-18 05:32 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/application/response/TokenResponse.java
> +    private boolean existHost;
좋습니다~

2022-07-18 05:48 UTC, meatsby approved these changes
수고하셨습니다!

2022-07-18 05:48 UTC, meatsby commented on backend/src/main/java/com/woowacourse/gongcheck/application/GithubOauthClient.java
> +    public String requestAccessToken(String code) {
```suggestion
    public String requestAccessToken(final String code) {
```

2022-07-18 05:48 UTC, meatsby commented on backend/src/main/java/com/woowacourse/gongcheck/application/GithubOauthClient.java
> +    public GithubProfileResponse requestGithubProfile(String accessToken) {
```suggestion
    public GithubProfileResponse requestGithubProfile(final String accessToken) {
```

2022-07-18 05:48 UTC, meatsby commented on backend/src/main/java/com/woowacourse/gongcheck/presentation/request/GithubAccessTokenRequest.java
> +    }
`@Getter` 가 있는데 필요할까요?!

2022-07-18 05:52 UTC, jinyoungchoi95 requested changes
리뷰내용이 반영된 커밋이 적용되어있지 않은 것 같네요 :)

추가적인 코멘트와 인수테스트가 없는데 추가 부탁드려요~

2022-07-18 05:52 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/application/response/GithubProfileResponse.java
> +    public static final String DEFAULT_SPACE_PASSWORD = "0000";
좋은것 같습니다 :)
어짜피 `@Builder`를 생성자 혹은 클래스단에 두는것에 대해서 큰 차이가 없으니까요

일관성있게 유지하려면 다른 entity들도 다 동일하게 구성해주어야할 것 같은데 이슈로 두고 백엔드팀 리팩터링 전체알림을 주시면 좋을 것 같습니다 :)

2022-07-18 05:52 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/application/GithubOauthClientTest.java
> +    private MockRestServiceServer mockRestServiceServer;
이거 무엇을 하는 역할인가요? ㅎㅎ

2022-07-18 05:52 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/application/GithubOauthClientTest.java
> +    void 깃허브_프로필을_요청한다() throws JsonProcessingException {
프로필 요청 시 프로필이 들어오지 않는 케이스는 없을까요?

2022-07-18 05:52 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/application/JjwtTokenProviderTest.java
> +    void 권한을_반환한다() {
권한 발급이 실패하는 케이스도 있으면 좋을 것 같네요

2022-07-18 05:52 UTC, jinyoungchoi95 commented on backend/src/test/resources/application.yml
> +    include: test
이거 이제 지워도 되지 않나요?

2022-07-18 06:14 UTC, kimchan123 commented on backend/src/test/java/com/woowacourse/gongcheck/application/GithubOauthClientTest.java
> +    private MockRestServiceServer mockRestServiceServer;
restTemplate를 이용하여 api 요청을 하는 메서드를 테스트 하고 싶을 때 활용하는 클래스 입니다!

2022-07-18 06:26 UTC, kimchan123 commented on backend/src/test/java/com/woowacourse/gongcheck/application/GithubOauthClientTest.java
> +    void 깃허브_프로필을_요청한다() throws JsonProcessingException {
테스트를 추가하였습니다~!

2022-07-19 06:35 UTC, jinyoungchoi95 approved these changes

2022-07-19 06:36 UTC, merged