[BE] host용 Job 생성 API를 구현한다
woowacourse-teams/2022-gong-check pull request #152
Opened 2022-07-16 06:15 UTC by cndqjacndqja

## issue
- resolve #141 

## 코드 설명
- host가 Job을 생성하는 API를 구현했습니다.
- Job을 생성할 때, Section, Task도 함께 한 번에 생성하게 합니다.

### 고민이 되었던 부분

Job 생성 시에 Section과 Task 또한 한 번에 생성하려다 보니, 현재 JobService가 너무 많은 Repository를 사용하고 있는 것은 아닌가 고민이 됐습니다

2022-07-16 08:19 UTC, awesomeo184 requested changes
고생하셨습니다~ 코멘트 하나 남겼는데 확인 부탁드려요~

2022-07-16 08:19 UTC, awesomeo184 commented on backend/src/main/java/com/woowacourse/gongcheck/application/JobService.java
> +            sectionRepository.save(createSection);
saveAll을 사용하는 방법을 고려해보는게 좋을 것 같아요!

2022-07-16 17:17 UTC, jinyoungchoi95 requested changes
고생하셨습니다~

몇가지 수정에 대한 코맨트와 말씀해주셨던 create 로직에 대한 코멘트 남겨두었습니다 :)
`cascade.PERSIST`에 대한 내용의 경우 고민해보시면서 구현하시다가 이해가 안가는 부분이 있으면 말씀해주세요 😀

2022-07-16 17:17 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/application/JobService.java
> +    public Long createJob(final Long hostId, final Long spaceId, final JobCreateRequest request) {
고민주셨던 부분이 이부분인 것 같아 여기에 제생각을 적어둡니다 :)

일단 `Job`이라는 도메인 하위에 `Section`과 `Task`가 있다라는 사실은 모두가 공감했던 이야기에요.
그렇다면 `Job` 도메인이 "저장"될 때 `Section`과 `Task`가 같이 저장된다라는 흐름 자체는 적절하다고 생각하는데요. 그럼 여기에서 Jpa에서의 `cascade.PERSIST`를 사용하면 좋을 것 같아요.

`Job`이라는 객체를 생성하는 시점에서 `Section`과 `Task`를 전부 객체만을 생성해서 같이 넣어주는거죠. (객체 생성시점에서는 repository의 호출 없이요) 그 후 save를 하면 알아서 다 persist될거에요.
다만 고려해야할 부분들이 너무 많기 때문에 팀적으로 도입하기 위해서는 모두가 cascade에 대한 이해가 있어야해서 해당 부분만 유의한다면 범고래가 생각한 중복에 대한 부분들이 어느정도 해소될것같네요 :)

주의점들 : https://joont92.github.io/jpa/CascadeType-PERSIST%EB%A5%BC-%ED%95%A8%EB%B6%80%EB%A1%9C-%EC%82%AC%EC%9A%A9%ED%95%98%EB%A9%B4-%EC%95%88%EB%90%98%EB%8A%94-%EC%9D%B4%EC%9C%A0/

2022-07-16 17:17 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/presentation/request/JobCreateRequest.java
> +    private String name;
`@NotNull`에 대한 검증도 있으면 좋을 것 같아요 :)

2022-07-16 17:17 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/presentation/request/JobCreateRequest.java
> +    @Valid
이렇게는 검증을 해보지 않았는데 `@Vaild`가 붙지 않는다면 해당 json값에 대해서는 검증을 하지 않나요?

2022-07-16 17:17 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/presentation/request/SectionRequest.java
> +    private String name;
`@ NotNull` 동일합니다~

2022-07-16 17:17 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/documentation/JobDocumentation.java
> +        void 작업의_이름_길이가_올바르지_않을_경우_예외가_발생한다() {
`작업` -> `Job` 아래와 영어, 한글이 혼용되어 사용되고 있는 것 같아요 :)

차후에 리팩터링하도록 논의된 부분이긴한데 지금부터 작성될 코드는 영어면 좋을 것 같아요 😄

2022-07-16 17:17 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/application/JobServiceTest.java
> +    void 공간과_섹션들과_작업들을_생성한다() {
다른 테스트는 `Host`의 미존재에 따른 예외 테스트를 진행하였는데 필요하지 않을까요?

`Space`에 대한 테스트도 포함일 것 같네요 :)

2022-07-16 17:17 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/application/JobServiceTest.java
> +        Long savedJob = jobService.createJob(host.getId(), space.getId(), jobCreateRequest);
```suggestion
        Long result = jobService.createJob(host.getId(), space.getId(), jobCreateRequest);
```
혹은 `savedJobId`가 더 직관적일 것 같아요 :)

2022-07-16 17:17 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/acceptance/JobAcceptanceTest.java
> +    void 작업의_이름이_1글자_미만_20글자_초과일_경우_예외가_발생한다(String input) {
```suggestion
    void 작업의_이름이_1글자_미만_20글자_초과일_경우_예외가_발생한다(final String input) {
```
조금은 사소한? 이슈입니다 😆

2022-07-16 17:17 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/acceptance/JobAcceptanceTest.java
> +    void 작업의_이름이_1글자_미만_20글자_초과일_경우_예외가_발생한다(String input) {
여기도 한글과 영어 도메인 이름에 대한 혼용처리가 되었으면 좋을 것 같네요 :)

2022-07-17 03:34 UTC, cndqjacndqja commented on backend/src/main/java/com/woowacourse/gongcheck/presentation/request/JobCreateRequest.java
> +    @Valid
네 테스트 해봤는데, `@Valid`를 붙여주지 않으니 검증을 하지 않더라구요! :)

2022-07-17 03:36 UTC, cndqjacndqja commented on backend/src/main/java/com/woowacourse/gongcheck/presentation/request/SectionRequest.java
> +    private String name;
Section, Task가 null인 상황도 존재한다고 생각해서, 이 부분은 수정할 때 `@NotNull`추가하지 않았습니다 :)

2022-07-17 05:17 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/presentation/request/SectionRequest.java
> +    private String name;
현재 name이 null인 상황이 없는 것 아닌가요?
현재 모든 로직이 새로 생성하는 로직인데 지금과 같이 구현될 경우 생성시 Section의 name에 null이 들어오는 문제가 발생할 것 같은데요?

2022-07-17 06:52 UTC, cndqjacndqja commented on backend/src/main/java/com/woowacourse/gongcheck/application/JobService.java
> +    public Long createJob(final Long hostId, final Long spaceId, final JobCreateRequest request) {
피드백 반영 과정에서 고민했던 부분들입니다.

### 고민 사항

처음에는 Sections를 생성한 후에 Job의 addAllSections메서드를 호출했습니다.(Task도 마찬가지였습니다.)
하지만 이렇게 될 경우, Sections를 생성하더라도 Job의 addAllSections 메서드를 호출하지 않으면 저장되지 않습니다.
Section을 생성할 때 강제적으로 Job의 sections에 add할 방법을 생각했습니다.

그러다 Section 생성자에는 Job의 sections에 add하는 메서드, Task 생성자에는 Section의 tasks에 add하는 메서드를 추가했습니다.
하지만 이런 메서드를 생성자에 추가하는 것이 맞나 고민이 됐습니다.

2022-07-17 07:05 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/application/JobService.java
> +    public Long createJob(final Long hostId, final Long spaceId, final JobCreateRequest request) {
add 메소드를 생성자에 추가한다는게 어떤걸 의미하는건지 이해가 잘 가지않아 코드를 보여주셔야할 것 같네요

제가 의도했던 방향은 단순히 각각 sections, tasks 필드를 두고 생성자에 추가하여 객체를 생성하는 방향이었습니다 :)

2022-07-18 06:51 UTC, meatsby requested changes
수고하셨습니다!
테스트에서 좀 더 고민해봤으면 하는 점들 리뷰로 남겨봤어요 확인해주세요~!

2022-07-18 06:51 UTC, meatsby commented on backend/src/main/java/com/woowacourse/gongcheck/application/JobService.java
> +        sections.forEach(i -> createSectionAndTasks(i, job));
```suggestion
        sections.forEach(sectionRequest -> createSectionAndTasks(sectionRequest, job));
```
이렇게 작성해보는건 어떨까용

2022-07-18 06:51 UTC, meatsby commented on backend/src/main/java/com/woowacourse/gongcheck/application/JobService.java
> +                .forEach(i -> createTask(i, section));
```suggestion
                .forEach(taskRequest -> createTask(taskRequest, section));
```
여기도요!

2022-07-18 06:51 UTC, meatsby commented on backend/src/test/java/com/woowacourse/gongcheck/acceptance/JobAcceptanceTest.java
> +        assertThat(response.statusCode()).isEqualTo(HttpStatus.BAD_REQUEST.value());
ParameterizedTest 에서 null 까지 한 번에 하는 건 어떨까용?
밑에도 마찬가지로요!

2022-07-18 06:51 UTC, meatsby commented on backend/src/test/java/com/woowacourse/gongcheck/application/JobServiceTest.java
> +        assertThat(savedJobId).isNotNull();
Space 에 Job 이랑 Section 이랑 Task 가 잘 들어갔는지 확인해보는건 어떨까용?

2022-07-18 07:28 UTC, awesomeo184 commented
브랜치 이름 컨벤션에 맞게 수정해주세요!

2022-07-18 09:47 UTC, meatsby approved these changes
수고하셨습니다!

2022-07-18 12:26 UTC, jinyoungchoi95 approved these changes

2022-07-18 13:03 UTC, kimchan123 approved these changes
고생하셨씁니다!!! 사소한 것 몇가지만 남겼습니다 ㅎ

2022-07-18 14:54 UTC, awesomeo184 approved these changes

2022-07-18 14:59 UTC, merged