[BE] SpaceServiceTest, SpaceRepositoryTest에 DCI 패턴을 적용한다.
woowacourse-teams/2022-gong-check pull request #317
Opened 2022-07-27 07:04 UTC by awesomeo184

## issue
- resolve #312 

## 코드 설명
- DCI 패턴 적용했습니다~

2022-07-27 07:43 UTC, cndqjacndqja approved these changes
수고하셨습니다 👍

2022-07-27 07:43 UTC, cndqjacndqja commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/SpaceServiceTest.java
> +            private Space space_1, space_2, space_3;
굳이 안 빼도 괜찮을 것 같아요! 테스트시에 해당 변수를 사용하지 않네요 :)

2022-07-27 10:16 UTC, meatsby requested changes
회의 때 나온 것들 위주로 체크해봤씀다!

2022-07-27 10:16 UTC, meatsby commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/SpaceServiceTest.java
> +                spaceRepository.saveAll(List.of(space_1, space_2, space_3));
saveAll 로 받은 리스트를 클래스 변수로 두고 비교하는 건 어떨까용

2022-07-27 10:16 UTC, meatsby commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/SpaceServiceTest.java
> +                        new MockMultipartFile("잠실 캠퍼스 사진", new byte[]{}));
이건 그냥 테스트 메서드 내부에 있어도 될것 같아용

2022-07-27 10:16 UTC, meatsby commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/SpaceServiceTest.java
> +            }
얘도요!

2022-07-27 10:16 UTC, meatsby commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/SpaceServiceTest.java
> +            }
SH

2022-07-27 10:16 UTC, meatsby commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/SpaceServiceTest.java
>              spaceRepository.saveAll(List.of(space1, space2));
space 가 2개나 필요한가요? 🤔

2022-07-27 10:16 UTC, meatsby commented on backend/src/test/java/com/woowacourse/gongcheck/core/domain/space/SpaceRepositoryTest.java
> +                        .build();
팩토리..?

2022-07-27 10:16 UTC, meatsby commented on backend/src/test/java/com/woowacourse/gongcheck/core/domain/space/SpaceRepositoryTest.java
> +                spaceRepository.saveAll(List.of(space_1, space_2, space_3));
List 받아서 검증하면 좋을 듯용

2022-07-27 10:16 UTC, meatsby commented on backend/src/test/java/com/woowacourse/gongcheck/core/domain/space/SpaceRepositoryTest.java
> +            anotherHost = hostRepository.save(Host_생성("4567", 4567L));
다른 호스트가 쓰이는 쪽에 쓰는건 어떨까요~?

2022-07-27 11:06 UTC, awesomeo184 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/SpaceServiceTest.java
> +            }
??

2022-07-27 11:46 UTC, jinyoungchoi95 requested changes
고생하셨습니다~

코맨트 확인부탁드려요 :)

2022-07-27 11:46 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/SpaceServiceTest.java
> +        class 입력받은_Host가_존재하는_경우 {
`findSpaces 메서드는 입력받은 Host가 존재하는 경우 해당 Host가 소유한 Space를 응답으로 반환한다`
보다는
`findSpaces 메서드는 존재하는 Host의 id를 입력받은 경우 해당 Host가 소유한 Space를 응답으로 반환한다`
가 더 자연스럽게 읽힐거라고 생각이 드네요 :)

2022-07-27 11:46 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/SpaceServiceTest.java
> +        class 입력받은_Host가_입력받은_Space_이름과_같은_Space를_이미_가지고_있는_경우 {
`createSpace 메서드는 입력받은 Host가 입력받은 Space 이름과 같은 Space를 이미 가지고 있는 경우`
보다는
 `createSpace 메서드는 Host가 입력받은 Space 이름과 같은 Space를 이미 가지고 있는 경우`
가 조금 더 잘 읽히는 것 같아요

2022-07-27 11:46 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/SpaceServiceTest.java
> +}
eol

2022-07-27 11:46 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/SpaceServiceTest.java
> +    class removeSpace_메서드는 {
host가 없는 경우, 다른 host의 space를 삭제하려는 경우도 추가하면 좋을 것 같네요 :)

2022-07-27 11:46 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/domain/space/SpaceRepositoryTest.java
> +                expected = spaceRepository.saveAll(List.of(space_1, space_2, space_3));
```suggestion
                expected = spaceRepository.saveAll(List.of(
                    Space_생성(host, "잠실 캠퍼스"), Space_생성(host, "선릉 캠퍼스"), Space_생성(host, "양평같은방"));
```
취향차이입니다만 사용하지 않는 필드를 선언해두는 것은 불필요한 라인이라고 생각하는 편입니다 :)

2022-07-27 11:46 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/domain/space/SpaceRepositoryTest.java
> +                assertThat(result).isEqualTo(expected);
```suggestion
                List<Space> result = spaceRepository.findAllByHost(host);
                
                assertThat(result).isEqualTo(expected);
```
한줄 띄우기 어떻게 생각하시나요?

2022-07-27 11:46 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/domain/space/SpaceRepositoryTest.java
> +    class getByHostAndId_메서드는 {
Describe는 단순히 `설명할 테스트 대상을 명시한다.`에 필요한 영역인데 대상에서 setUp을 하는 것은 조금 부적절하지 않을까요?
그때문에 Context가 많이 무거워질 수는 있으나 반복적으로 테스트값세팅을 해야한다면 값 세팅을 하기위한 메소드로 분리하여 호출하면 해결할 수 있는 영역으로 보여요

2022-07-27 11:46 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/domain/space/SpaceRepositoryTest.java
> +            }
```suggestion
            private Long spaceId;
            private Host anotherHost;

            @BeforeEach
            void setUp() {
                spaceId = spaceRepository.save(Space_생성(host, "잠실 캠퍼스"));
                    .getId();
                anotherHost = hostRepository.save(Host_생성("4567", 4567L));
            }
```

2022-07-27 11:46 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/domain/space/SpaceRepositoryTest.java
> +            host = hostRepository.save(Host_생성("1234", 1234L));
위와 동일한 Descirbe에서 값 세팅을 하는것이 맞느냐입니다~

2022-07-27 11:46 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/domain/space/SpaceRepositoryTest.java
> +}
eol

2022-07-27 12:20 UTC, awesomeo184 commented on backend/src/test/java/com/woowacourse/gongcheck/core/domain/space/SpaceRepositoryTest.java
> +                expected = spaceRepository.saveAll(List.of(space_1, space_2, space_3));
살짝 고민했던 부분인데, 반영하도록 하겠습니당~

2022-07-27 12:35 UTC, awesomeo184 commented on backend/src/test/java/com/woowacourse/gongcheck/core/domain/space/SpaceRepositoryTest.java
> +    class getByHostAndId_메서드는 {
Describe에서 셋업하던 것을 모두 Context로 이동하였습니다.

2022-07-27 15:01 UTC, kimchan123 requested changes
고생하셨습니다! 사소한 것들이에요

2022-07-28 01:09 UTC, kimchan123 approved these changes

2022-07-28 02:27 UTC, jinyoungchoi95 approved these changes
고생하셨습니다~

리뷰 남긴거 확인만 부탁드려요~

2022-07-28 02:27 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/domain/space/SpaceRepositoryTest.java
> +            private Host host;
```suggestion
private Host host;
private Name name;
```
`name`은 위로 빼도될거같네요

2022-07-28 04:15 UTC, merged