[BE] DCI 패턴을 적용한 JobService, JobRepository 테스트 코드를 수정한다.
woowacourse-teams/2022-gong-check pull request #318
Opened 2022-07-27 07:29 UTC by cndqjacndqja

## issue
- resolve #308 

## 코드 설명
- JobService, JobRepository 테스트에 DCI 패턴을 적용했습니다.

2022-07-27 10:51 UTC, awesomeo184 requested changes
고생하셨습니다. 아무래도 처음 적용하는 패턴이다보니까 시작할 때 팀 컨벤션을 확실히 잡는게 좋을 것 같아서 코멘트가 많아졌네요~ 확인 부탁드릴게요

2022-07-27 10:51 UTC, awesomeo184 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +
목록이 세 개라는게 이 테스트의 관심사가 맞을까요?

2022-07-27 10:51 UTC, awesomeo184 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +            }
테스트 이름은 "한번에 생성한다"인데 검증은 job 생성에 대한 것만 하고 있네요, 개선할 방법이 있을까요??

2022-07-27 10:51 UTC, awesomeo184 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +
여기도 윗부분과 마찬가지!

2022-07-27 10:51 UTC, awesomeo184 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +            }
```suggestion
            @Test
            void 기존에_존재하던_Job을_삭제한_후_새로운_Job을_생성한다() {
                Long updateJobId = jobService.updateJob(host.getId(), savedJobId, request);

                assertThat(updateJobId).isNotNull();
            }
```

이렇게 해도 괜찮지 않을까요? 엄밀히 말하면 수정하는게 아니니까요!

테스트 이름에 기존에 존재하는 Job을 삭제한 후, 라고 되어있는데 이 부분에 대한 검증도 필요하지 않을까요?

2022-07-27 10:51 UTC, awesomeo184 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +
```suggestion
        @Nested
        class 입력받은_Job_id가_존재하지_않는_경우 {

```
이렇게 하면 테스트 전체를 읽을 때 더 자연스럽지 않을까요?

2022-07-27 10:56 UTC, meatsby requested changes
회의 때 나온 내용 위주로 짚어봤씀당

2022-07-27 10:56 UTC, meatsby commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +                assertThat(result.getJobs()).hasSize(3);
saveAll 받아서 Job 끼리 비교하는 건 어떨까용

2022-07-27 10:56 UTC, meatsby commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +                assertThatThrownBy(() -> jobService.findJobs(0L, 1L))
1L 말고 실제 jobId 를 넣어보는건 어떨까용

2022-07-27 10:56 UTC, meatsby commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +                List<SectionCreateRequest> sections = List.of(new SectionCreateRequest("대강의실", tasks));
요거 전체는 `createJob_메서드는` 의 Nested 에서 해주면 어떨까용

2022-07-27 10:56 UTC, meatsby commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +                savedJobId = jobService.createJob(host.getId(), space.getId(), request);
요것도 마찬가지!

2022-07-27 10:56 UTC, meatsby commented on backend/src/test/java/com/woowacourse/gongcheck/core/domain/job/JobRepositoryTest.java
> +                job_2 = jobRepository.save(Job_생성(space, "마감"));
List<Job> 으로 받고 containsAll 해서 비교하는건 어떨까요?

2022-07-27 10:59 UTC, jinyoungchoi95 requested changes
고생하셨습니다~

어썸오 코맨트와 더불어서 제 의견을 남겨두었으니 좋은 의견있으면 수렴부탁드려요 :)
다른 부분들도 포함되는 부분이 많으나 중복되는 부분이 있어 rc는 전체적으로 다 걸어져있다라고 생각해주세요~

2022-07-27 10:59 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +                jobRepository.saveAll(List.of(job_1, job_2, job_3));
```suggestion
                jobRepository.saveAll(List.of(Job_생성(space, "오픈"), Job_생성(space, "청소"), Job_생성(space, "마감")));
```
아까 이야기한대로 현재는 지금과 같이 수정하는것이 좋을 것 같네요
만약 구체적인 검증이 필요하다면 context class(Job_목록이_세개가_있는_경우) 변수로 값을 두고 세팅하는걸로!

2022-07-27 10:59 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +        }
```suggestion
        class 다른_Host의_Space의_Job_목록을_조회할_경우 {

            private Host host;
            private Space space;

            @BeforeEach
            void setUp() {
                host = hostRepository.save(Host_생성("1234", 1234L));
                Host otherHost = hostRepository.save(Host_생성("1234", 2345L));
                space = spaceRepository.save(Space_생성(otherHost, "잠실"));
            }

            @Test
            void 예외를_발생시킨다() {
                assertThatThrownBy(() -> jobService.findJobs(host.getId(), space.getId()))
                        .isInstanceOf(NotFoundException.class)
                        .hasMessage("존재하지 않는 공간입니다.");
            }
        }
```
host가 테스트하는 주체가되고 다른 호스트의 space를 진행한다라는 행위이기 때문에 이렇게 변경하는게 어떨까요?

2022-07-27 10:59 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +        class Host가_존재하지_않는데_Job을_생성하려는_경우 {
입력받은 Host id가 존재하지 않는 경우라기 보다는 "존재하지 않는  Host의 id를 입력받은 경우"가 더 자연스럽지 않을까요?

2022-07-27 10:59 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +        class host가_존재하지_않는_경우 {
위 어썸오 코맨트와 더불어서 여기도 "존재하지 않는  Host의 id를 입력받은 경우"가 자연스러울거같네요

2022-07-27 10:59 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +        class host에_해당하는_jobId가_아닐_경우 {
"다른 host의 job id를 입력받은 경우"

2022-07-27 10:59 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +
"존재하지 않는 job id를 입력받을 경우"는요?.?

2022-07-27 13:13 UTC, cndqjacndqja commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +                List<SectionCreateRequest> sections = List.of(new SectionCreateRequest("대강의실", tasks));
이 부분은 현재 Nested 중, Context에 해당하는 영역에서 세팅해 주고 있는걸로 통일해서
변경하기 전에 팀원과 협의가 필요할 것 같네요! 일단은 남겨놓고 내일 얘기해보죠! :)

2022-07-28 01:17 UTC, kimchan123 requested changes
고생하셨습니다!!!!!

2022-07-28 01:17 UTC, kimchan123 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +                );
꼼꼼한 테스트 굿!

2022-07-28 01:17 UTC, kimchan123 commented on backend/src/test/java/com/woowacourse/gongcheck/core/domain/job/JobRepositoryTest.java
> +                job = jobRepository.save(Job.builder()
행위 검증 대상이 save 메서드인데 setUp에 있으면 안될 것 같아요~!

2022-07-28 02:24 UTC, jinyoungchoi95 requested changes
코멘트가 좀 많은데 중복되는 부분들 생략안하고 전부 포함하였으니 확인부탁드려요 :)

2022-07-28 02:24 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +            private final Long NON_EXIST_HOST_ID = 0L;
```suggestion
            private static final long NON_EXIST_HOST_ID = 0L;
            private Host host;
            private Space space;
```
순서와 상수에 대한 내용 :)

2022-07-28 02:24 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +            private final Long NON_EXIST_SPACE_ID = 0L;
```suggestion
            private static final long NON_EXIST_SPACE_ID = 0L;
            private Long hostId;
```
여기도 마찬가지입니다~

2022-07-28 02:24 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +                                .containsAll(sectionCreateRequestNames)
```suggestion
                        () -> assertThat(savedTasks)
                                .extracting(Task::getName)
                                .containsAll(taskCreateRequestNames),
                        () -> assertThat(savedSections)
                                .extracting(Section::getName)
                                .containsAll(sectionCreateRequestNames)
```
개인적으로 띄우는게 낫다라는 의견입니다~

2022-07-28 02:24 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +            private final Long NON_EXIST_HOST_ID = 0L;
```suggestion
            private static final long NON_EXIST_HOST_ID = 0L;
            private Space space;
            private JobCreateRequest request;
```

2022-07-28 02:24 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +            private final Long NON_EXIST_SPACE_ID = 0L;
```suggestion
            private static final long NON_EXIST_SPACE_ID = 0L;
            private Host host;
            private JobCreateRequest request;
```

2022-07-28 02:24 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +    class createJob_메소드는 {
다른 host의 space에 createJob을 하는 경우에 대한 테스트도 추가해주세요~

2022-07-28 02:24 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +            private final Long NON_EXIST_HOST_ID = 0L;
```suggestion
            private static final long NON_EXIST_HOST_ID = 0L;
            private JobCreateRequest request;
            private Long savedJobId;
```

2022-07-28 02:24 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +                private final Long NON_EXIST_JOB_ID = 0L;
```suggestion
        @Nested
        class findSlackUrl_메소드는 {

            @Nested
            class 존재하지_않는_Host의_id를_입력받은_경우 {

                private static final long NON_EXIST_HOST_ID = 0L;
                private static final long JOB_ID = 1L;
                
                @Test
                void 예외가_발생한다() {
                    assertThatThrownBy(() -> jobService.findSlackUrl(NON_EXIST_HOST_ID, JOB_ID))
                            .isInstanceOf(NotFoundException.class)
                            .hasMessage("존재하지 않는 호스트입니다.");
                }
            }

            @Nested
            class Job이_존재하지_않는_경우 {

                private static final long NON_EXIST_JOB_ID = 0L;
                private Host host;
```

2022-07-28 02:24 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +                private final Long NON_EXIST_JOB_ID = 0L;
복합적으로 다들어가있습니다~

2022-07-28 02:24 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +            private Job job;
```suggestion
            private static final String SLACK_URL = "http://slackurl.com";
            private Host host;
            private Job job;
```
조금 중요한 상수인듯해서 빼는게 좋을 것 같네요 :)

2022-07-28 02:24 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +            private final Long NON_EXIST_JOB_ID = 0L;
```suggestion
            private static final long NON_EXIST_HOST_ID = 0L;
            private static final long JOB_ID = 1L;
            private SlackUrlChangeRequest request;
```

2022-07-28 02:24 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +            private final Long NON_EXIST_JOB_ID = 0L;
```suggestion
            private static final long NON_EXIST_JOB_ID = 0L;
            private SlackUrlChangeRequest request;
            private Host host;
```

2022-07-28 02:24 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +        class 존재하는_Job을_입력_받는_경우 {
여기도 slack url을 상수로 분리해주세요 ~

2022-07-28 02:26 UTC, kimchan123 approved these changes
고생하셨습니다~!

2022-07-28 04:19 UTC, awesomeo184 approved these changes
고생많으셨습니다. 마이너하지만 상수 개행 부분 컨벤션 수정해주시면 될 것 같아요. 어프루브 하겠습니다.

2022-07-28 04:19 UTC, awesomeo184 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +            private Host host;
상수는 개행으로 분리해주는 컨벤션을 확인해주세요!

2022-07-28 04:19 UTC, awesomeo184 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +            private long hostId;
상수 개행!

2022-07-28 07:24 UTC, jinyoungchoi95 approved these changes

2022-07-29 03:07 UTC, meatsby approved these changes

2022-07-29 04:21 UTC, merged