[BE] Host, Guest Auth연관 클래스와 HostRepository에 DCI 패턴을 적용한다.
woowacourse-teams/2022-gong-check pull request #320
Opened 2022-07-27 07:33 UTC by jinyoungchoi95

## issue
- resolve #319 

## 코드 설명
- HostSerivce, GuestService, GithubOauthClient, HostRepository

2022-07-27 10:39 UTC, meatsby approved these changes
LGTM

2022-07-27 11:11 UTC, cndqjacndqja approved these changes
수고하셨습니다 👍

2022-07-28 00:46 UTC, awesomeo184 requested changes

2022-07-28 01:20 UTC, kimchan123 requested changes
고생하셨습니다~! 사소한 것 한가지 남겼어요 ㅎㅎ

2022-07-28 01:40 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/auth/application/GuestAuthServiceTest.java
> +                assertThatThrownBy(() -> guestAuthService.createToken(0L, guestEnterRequest))
0L로는 어색했었는데 좋은 것 같습니다 :)

2022-07-28 01:55 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/domain/host/HostRepositoryTest.java
> +        class 저장할_호스트를_받는_경우 {
감사합니다~

2022-07-28 01:56 UTC, awesomeo184 approved these changes

2022-07-28 01:58 UTC, kimchan123 approved these changes
고생하셨습니다~!

2022-07-28 02:01 UTC, merged