[BE] DCI 패턴을 적용한 TaskService, RunningTaskService, TaskRepository, RunningTaskRepository 테스트 코드를 수정한다.
woowacourse-teams/2022-gong-check pull request #321
Opened 2022-07-27 07:40 UTC by meatsby

## issue
- resolve #309 

## 코드 설명
- DCI 패턴 적용

2022-07-27 11:34 UTC, jinyoungchoi95 requested changes
수고하셨습니다~

일단 전체적으로 동일한 형태의 리뷰가 지속될 것 같아 하나의 코멘트만 남겨두었습니다.
setUp에서 `respository.save()`가 너무 지속적으로 반복이 된다면 반복되는 생성 부분을 메소드의 형태로 두고, `Context`의 setUp에서 호출하는게 더 DCI 패턴에 맞지 않을까 싶어요
`Describe`는 말그대로 `설명할 테스트 대상을 명시한다.`이기 때문에 상황을 설정하는 것과는 거리가 멀다라고 생각합니다.

확인해보시고 dm이나 코멘트 주세요 :)

2022-07-27 11:34 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/TaskServiceTest.java
> +        }
현재 하고자하는 DCI는 다음과 같이 보이는데요.

```
D : createNewRunningTasks 메소드는
C : 존재하는 Host의 id와 Task의 id를 입력하는 경우
I : 새로운 Running Task를 생성한다
```
테스트의 네이밍은 위에서 제 의견이 들어갔다라고 생각해주세요 :)

그렇게 과연 79-91번라인까지의 setUp은 존재하는 것에 대한 테스트이므로 96-99의 setUp에 있어야하지 않을까요?

또한 It의 경우 "대상의 행동"을 지칭하기 때문에 저희가 현재 테스트에서의 주 관심사인 `createNewRunningTasks`는 setUp에 있는 것이 아닌 Test에 있어야할 것 같아요. 결과적으론 아래와 같은 형태로요

```java
@Test
void 새로운_Running_Task를_생성한다() {
    taskService.createNewRunningTasks(host.getId(), job.getId());
    List<RunningTask> actual = runningTaskRepository.findAllById(taskIds);

    assertThat(actual).hasSize(2);
}

2022-07-27 11:34 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/TaskServiceTest.java
> +        }
위와 더불어서 그렇다라면 Host를 생성하는 것은 해당 "D"에서의 setUp에서 행해주어야겠네요

2022-07-28 00:50 UTC, awesomeo184 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/TaskServiceTest.java
> +        }
저도 이 부분 수정되면 다시 리뷰하도록 할게요

2022-07-28 07:25 UTC, jinyoungchoi95 approved these changes

2022-07-29 03:08 UTC, cndqjacndqja approved these changes
수고하셨습니다 👍

2022-07-29 08:37 UTC, kimchan123 approved these changes

2022-07-29 08:37 UTC, awesomeo184 approved these changes

2022-07-29 08:39 UTC, merged