[BE] Job 생성 시 section과 task의 설명을 추가할 수 있도록 수정한다.
woowacourse-teams/2022-gong-check pull request #352
Opened 2022-08-01 10:24 UTC by jinyoungchoi95

## issue
- resolve #346

## 코드 설명
- 앞선 pr #350 처럼 job 생성 시에도 section과 task의 설명을 추가할 수 있도록 변경
- 설명, 이미지링크 두개를 받을 수 있으며 해당 필드의 경우 둘다 nullable하게 설정완료

## 추가사항
임의로 다음과 같은 schema를 지정하였습니다
- 설명 : `description`
- 이미지 링크 : `imageUrl`

또한 해당 값들의 경우 특정한 설명에 해당하므로 `@Embeddable`로써 각각 `SectionExplanation`과 `TaskExplanation`에서 관리할 수 있도록 변경하였습니다.
네이밍에서 추가적인 의견이 있거나 분리한 상태에 대해서 의견이 있으시다면 코맨트 부탁드립니다

2022-08-01 12:59 UTC, cndqjacndqja approved these changes
수고하셨습니다 👍

2022-08-02 01:03 UTC, awesomeo184 requested changes
고생하셨습니다. 코멘트 하나 남겼어요~

2022-08-02 03:36 UTC, kimchan123 approved these changes
고생하셨습니다~!!

2022-08-02 03:36 UTC, kimchan123 commented on backend/src/main/java/com/woowacourse/gongcheck/core/domain/section/SectionExplanation.java
> +        if (Objects.isNull(description)) {
이 메서드는 람다식에서만 사용하는걸 권장하는 것 같더라구요!
`
API Note:
This method exists to be used as a java.util.function.Predicate, filter(Objects::isNull)
`

2022-08-02 03:36 UTC, kimchan123 commented on backend/src/main/java/com/woowacourse/gongcheck/core/domain/task/TaskExplanation.java
> +}
eq & hs 굿!

2022-08-02 03:36 UTC, kimchan123 commented on backend/src/main/java/com/woowacourse/gongcheck/core/domain/task/TaskExplanation.java
> +            throw new IllegalArgumentException("task의 설명은 " + DESCRIPTION_MAX_LENTH + "자 이하여야합니다.");
오늘 회의에 따르면 BusinessException으로 변경해야 할 것 같아요~!

2022-08-02 03:38 UTC, kimchan123 approved these changes

2022-08-02 04:19 UTC, awesomeo184 approved these changes
고생하셨습니다!

2022-08-02 05:12 UTC, meatsby requested changes

2022-08-02 05:12 UTC, meatsby commented on backend/src/main/java/com/woowacourse/gongcheck/core/domain/section/SectionExplanation.java
> +            throw new IllegalArgumentException("section의 설명은 " + DESCRIPTION_MAX_LENTH + "자 이하여야합니다.");
여기도 Business 로 바꿔야할듯요!

2022-08-02 05:12 UTC, meatsby commented on backend/src/test/java/com/woowacourse/gongcheck/core/domain/section/SectionExplanationTest.java
> +    }
nice

2022-08-02 05:12 UTC, meatsby commented on backend/src/test/java/com/woowacourse/gongcheck/documentation/JobDocumentation.java
> +                                    tasks2));
예시가 아주 나이스하네용

2022-08-02 05:15 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/core/domain/section/SectionExplanation.java
> +        if (Objects.isNull(description)) {
해당 내용은 제가 느끼기엔 람다식에서만이라기보다는 존재한 당초의 이유가 람다식을 위해서로 보이네요

`description == null`과 `Objects.isNull(description)`에 대한 사용을 생각했을 때는 저는 `isNull`이 ==에 대한 하드코딩도 줄이고 의미를 잘 전달한다라고 생각하는데 어떻게 생각하시나요?

2022-08-02 05:25 UTC, meatsby approved these changes
수고하셨습니다!

2022-08-02 05:26 UTC, kimchan123 commented on backend/src/main/java/com/woowacourse/gongcheck/core/domain/section/SectionExplanation.java
> +        if (Objects.isNull(description)) {
저도 isNull 쪽이 훨씬 의미 전달이 잘 된다고 느껴지네요 ㅎㅎ

2022-08-02 05:33 UTC, merged