[BE] 로깅을 적용한다.
woowacourse-teams/2022-gong-check pull request #359
Opened 2022-08-01 13:41 UTC by meatsby

## issue
- resolve #354 

## 코드 설명
- 현재 logback-access 를 통해 HTTP Request 와 Response 를 확인할 수 있습니다.
- ControllerAdvice 를 통해 로깅을 적용했고, `Error` 의 경우 어느 부분에서 에러가 발생하였는지 확인하기 위해 StackTrace 를 로그에 남기도록 하였습니다.
- AOP 를 사용하여 어떤 클래스.메서드에서 예외가 발생하였는지 확인할 수 있도록 리팩터링할 예정입니다.

2022-08-02 01:09 UTC, awesomeo184 requested changes
코멘트 남긴부분이랑 회의때 얘기한 부분 참고해서 코멘트 달아주세용~

2022-08-02 01:09 UTC, awesomeo184 commented on backend/src/main/java/com/woowacourse/gongcheck/exception/ControllerAdvice.java
> +        log.error("Stack Trace : {}", stackTrace);
e.getStacktrace()로 꺼내와서 찍는거랑 어떻게 다른건가요?

2022-08-02 03:30 UTC, meatsby commented on backend/src/main/java/com/woowacourse/gongcheck/exception/ControllerAdvice.java
> +        log.error("Stack Trace : {}", stackTrace);
e.getStackTrace() 를 하면 개행 없이 모든 라인이 붙어서 출력되는 반면, printWriter 를 통해 자동 개행을 추가하여 개발단에서 볼 수 있는 stackTrace 와 같은 형식으로 볼 수 있습니다.

2022-08-02 05:32 UTC, jinyoungchoi95 requested changes
수고하셨습니다~

코맨트 확인 부탁드려요 :)

2022-08-02 05:32 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/exception/ControllerAdvice.java
> +        log.info(e.getMessage());
레벨 | 설명
-- | --
Fatal | 넌 이미 죽어있다
Error | 의도하지 않은 에러가 발생한 경우 (ex. Github 에 엑세스 토큰을 받는 과정에서 credential 이 잘못된 경우) 이건 우리가
Warn | 명확한 의도가 있는 에러 (ex. NotFoundException, Apache에서 제공한 로깅 그거를 봅시다.) 시스템 구조 상 클라이언트가 잘못 보낼 수 가 없는데 누군가 POSTMAN 으로 헛짓거리를 한다. 이건 나쁜거다.
Info | 요구사항에 따라 시스템 동작을 보여줄 때 대략적인 수준에서 응용 프로그램의 진행상황을 강조하는 정보 메시지로 사용
Debug | Info 레벨보다 더 자세한 정보가 필요한 경우. Dev 환경
Trace | Debug 레벨보다 더 자세함. Dev 환경에서 버그를 해결하기 위해 사용

지정했던 에러로깅 레벨에 대한 표를 보면 info의 경우 시스템 동작을 보여주는 것이고 `UnauthorizedException`은 사용자 인증에 대한 에러이므로 `Warn`에 더 가깝지 않을까요?

2022-08-02 05:32 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/exception/ControllerAdvice.java
> +        log.info(e.getMessage());
여기도 사용자 예외인데 `Warn`이 더 적절하다고 생각이 드네요

2022-08-02 05:32 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/exception/ControllerAdvice.java
> +        e.printStackTrace(printWriter);
`e.printStackTrace()`와는 어떤 차이가 있어 해당 로직을 도입하시게 되신건가요?

+ 해당 부분은 메소드로 빼는 것이 좋다라고 생각합니다

2022-08-02 05:32 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/exception/ControllerAdvice.java
> +    public ResponseEntity<ErrorResponse> handleInfrastructureException(final InfrastructureException e) {
인프라 관련된 로직인데 예외를 그대로 내보내기보다는 하단의 `서버 에러가 발생했습니다.`를 쓰는것이 좋지 않을까요?
사용자에게 저희가 사용하는 외부 라이브러리에 대한 에러 메시지를 전부 보여주지 않아도 될 것 같습니다

2022-08-02 05:32 UTC, jinyoungchoi95 commented on backend/src/main/resources/logback/properties/default-properties.xml
> +              value="${CONSOLE_LOG_PATTERN:-%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t
`.%M`으로 발생하는 변경점이 어떻게 되나요?

2022-08-02 06:11 UTC, kimchan123 requested changes
good!

2022-08-02 06:11 UTC, kimchan123 commented on backend/src/main/java/com/woowacourse/gongcheck/exception/ControllerAdvice.java
> +        log.info(e.getMessage());
저도 Warn이라고 생각이 드는데 논의해보면 좋을 것 같아요~!

2022-08-02 10:33 UTC, meatsby commented on backend/src/main/java/com/woowacourse/gongcheck/exception/ControllerAdvice.java
> +        log.info(e.getMessage());
현재 공간 입장 비밀번호를 잘못 입력하였을 경우 UnauthorizedException 을 던지고 있습니다. 사용자 인증에 관한 부분에 대해서만 고려한다면 현재 애플리케이션 구조 외부에서의 요청이라고 생각할 수 있기 때문에 Warn 이라고 로깅을 남기는 것이 맞을 것 같습니다. 그렇다면 현재 공간 입장 비밀번호가 틀린 예외를 다른 예외로 분류해야 할까요?

2022-08-02 10:35 UTC, meatsby commented on backend/src/main/resources/logback/properties/default-properties.xml
> +              value="${CONSOLE_LOG_PATTERN:-%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t
콘솔 단에서 로깅을 수행할 경우 해당 로깅의 클래스 및 메서드까지 출력됩니다.

2022-08-02 10:41 UTC, meatsby commented on backend/src/main/java/com/woowacourse/gongcheck/exception/ControllerAdvice.java
> +        log.info(e.getMessage());
BusinessException 에 `사용자가 이미 존재하는 공간의 이름으로 새로운 공간을 생성한다` 라는 예외가 존재하는데요. 이는 위에서 언급한 비밀번호를 잘못 입력한 상황과 같이 사용자가 애플리케이션을 사용하면서 충분히 경험할 수 있는 예외 같은데, 이런 예외들은 Warn 이라고 봐야할까요?

`Warn` 이 시스템 구조 상에서 발생할 수 없는 Exception 에 대한 로깅이라고 판단하고 있는데 그렇다면 애플리케이션 사용중 발생 가능한 사용자 예외는 `Info` 레벨로 작성해야하지 않을까요?

그렇다면 이를 판단하기 위해 새로운 Exception 을 추가해야할까요?

2022-08-02 10:47 UTC, meatsby commented on backend/src/main/java/com/woowacourse/gongcheck/exception/ControllerAdvice.java
> +    public ResponseEntity<ErrorResponse> handleInfrastructureException(final InfrastructureException e) {
현재 InfraStructureException 은 외부 라이브러리 사용 클래스에서 외부 라이브러리 에러 메시지를 log 를 통해 출력하고 사용자를 위한 에러 메시지를 새롭게 반환하게 있습니다.

슬랙 -> 메시지 전송에 실패했습니다.
깃헙 -> 해당 사용자의 프로필을 요청할 수 없습니다.

이런 메시지도 보내주지 않는 것이 좋다는 말씀이실까요?

2022-08-03 02:29 UTC, awesomeo184 commented on backend/src/main/java/com/woowacourse/gongcheck/exception/ControllerAdvice.java
> +        log.info(e.getMessage());
사용자가 비밀번호를 잘못 입력했을때는 info로 로그를 찍는게 맞다고 생각해요. Jwt 관련 로직에 문제로 발생하는 에러는 warn이 맞다고 생각하구요. 이 둘을 분리해서 로깅을 하는것은 어떤가요?

2022-08-03 03:55 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/exception/ControllerAdvice.java
> +    public ResponseEntity<ErrorResponse> handleInfrastructureException(final InfrastructureException e) {
잘못봤네요 좋은 것 같습니다 :)

2022-08-03 03:57 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/exception/ControllerAdvice.java
> +        log.info(e.getMessage());
> 명확한 의도가 있는 에러 (ex. NotFoundException, Apache에서 제공한 로깅 그거를 봅시다.) 시스템 구조 상 클라이언트가 잘못 보낼 수 가 없는데 누군가 POSTMAN 으로 헛짓거리를 한다. 이건 나쁜거다.

WARN에 해당하는 에러에 대한 정보인데요, 그렇다면 NotFoundException에 대한 부분에 대해서 따로 관리를 해야하지 않을까요?
이렇게 분산되게 된다면 INFO와 WARN에 대한 기준점을 다시 잡아보는 것도 좋을 것 같다라는 생각이 드네요

2022-08-03 09:47 UTC, awesomeo184 approved these changes

2022-08-04 01:38 UTC, jinyoungchoi95 approved these changes
수고하셨습니다~

2022-08-04 01:53 UTC, awesomeo184 approved these changes

2022-08-04 01:53 UTC, awesomeo184 commented on backend/src/main/resources/logback/slack/slack-appender.xml
> +</included>
이건 역할이 뭔가요?

2022-08-04 02:29 UTC, meatsby commented on backend/src/main/resources/logback/slack/slack-appender.xml
> +</included>
외부 라이브러리 사용에 필요한 설정입니다.

2022-08-04 02:36 UTC, merged