[BE] Service 테스트에 대한 구체적인 테스트 검증을 추가한다.
woowacourse-teams/2022-gong-check pull request #367
Opened 2022-08-02 06:37 UTC by cndqjacndqja

## issue
- resolve #353 

## 코드 설명
- Service 테스트에서 Id가 notNull인지만 확인하는 등의 검증이 부족한 부분을 보완했습니다.
- 생성된 submission의 name이 올바른지도 검증하기 위해 `Submission_생성` 픽스쳐 메서드에 name을 주입 받는 것으로 수정했습니다.
- actual에서 get() 해온 변수명은 actual~로 지정했습니다 (ex. actual.getTasks() -> actualTasks)

2022-08-03 03:51 UTC, awesomeo184 approved these changes
고생 많으셨습니다. 추후에 논의해볼만한 사항 몇개 적었어요. 메모해두고 다음에 한번 논의해봐야겠네요

2022-08-03 04:03 UTC, jinyoungchoi95 requested changes
수고하셨습니다~

코맨트 확인 부탁드려요

2022-08-03 04:03 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/SpaceServiceTest.java
> +                        () -> assertThat(actual.getId()).isEqualTo(spaceId),
`spaceId`를 통해서 값을 가져왔는데 이 검증은 뭔가 getById에 대한 검증이 되는 것 같은 느낌이 드네요.
확인해보시고 같은 의견이시라면 제거해주세요 ~

2022-08-03 04:03 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/SubmissionServiceTest.java
> +                                        .containsExactly(job.getId(), job.getId()),
```suggestion
                                .extracting(SubmissionResponse::getJobId)
                                .containsExactly(job.getId(), job.getId()),
```
줄바꿈 확인해주세요

2022-08-03 04:03 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/TaskServiceTest.java
> +                                .containsAll(taskIds),
두개를 분리한 이유가 있을까요? 두 값을 동시에 테스트할 수 있는 방법이 있으니 확인해주세요

```java
assertThat(actual)
            .extracting(RunningTask::isChecked, RunningTask::getTaskId)
            .contains(
                    tuple(false, 1L),
                    tuple(false, 2L)
            );
```

2022-08-03 04:03 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/TaskServiceTest.java
> +                );
위와 같은 코멘트입니다

2022-08-03 04:54 UTC, cndqjacndqja commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/HostServiceTest.java
>                          .getId();
현재 `GITHUB_ID`도 검증에서 추가했기 때문에 상수로 뺐습니다!

2022-08-03 04:55 UTC, cndqjacndqja commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/TaskServiceTest.java
> +                );
네 테스트마다 다르게 쓰였는데 `usingRecursiveComparision`보다 현재 방식이 더 많길래 통일성을 주기 위해 `usingRecursiveComparision`를 쓸 수 있는 상황에도 보기와 같이 했습니다!
논의해보면 좋을 것 같네요

2022-08-03 04:56 UTC, cndqjacndqja commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/SpaceServiceTest.java
> +                        () -> assertThat(actual.getId()).isEqualTo(spaceId),
다른 id 검증은 필요하다고 생각되지만, 이 로직은 불필요하다고 생각해서 제거했습니다~!

2022-08-03 04:59 UTC, meatsby requested changes
수고 많으셨습니다!

2022-08-03 04:59 UTC, meatsby commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/HostServiceTest.java
> +
개행 하나 지워주세요!

2022-08-03 04:59 UTC, meatsby commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/SubmissionServiceTest.java
> +                                .containsExactly(SUBMISSION_AUTHOR, SUBMISSION_AUTHOR),
먼가 3개의 각기 다른 Submission 에 대해 검증하려면 차이점이 있으면 좋을 것 같아요!
현재 바꿀 수 있는게 Submission_Author 정도니 각기 다른 제출자를 가지고 있도록 만들어보면 어떨까요?
아니면 Host 에 새로운 Job 을 추가하는 것도 방법인 것 같아요!

2022-08-03 04:59 UTC, meatsby commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/TaskServiceTest.java
> +                                .containsExactly(TASK_NAME_1, TASK_NAME_2)
```suggestion
                        () -> assertThat(actualTasks)
                                .extracting(RunningTaskResponse::getName)
                                .containsExactly(TASK_NAME_1, TASK_NAME_2)
```
개행해주세용

2022-08-03 05:05 UTC, cndqjacndqja commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/TaskServiceTest.java
> +                );
저 상태에서 tuple로 묶어서 검증할 수 있을까요?? actual과 actualTasks가 달라서 위 코멘트와 같이 변경이 어려울 것 같은데 제가 못 찾은 것일까요 😂

2022-08-03 05:14 UTC, cndqjacndqja commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/TaskServiceTest.java
> +                                .containsAll(taskIds),
왜 인지 모르겠으나... 말씀해주신 코드로 작성하면, 전체 테스트 시 격리가 되지 않는 문제를 발견했습니다! 문제가 무엇인지는 좀 더 찾아보겠습니다.

2022-08-03 05:19 UTC, cndqjacndqja commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/TaskServiceTest.java
> +                                .containsAll(taskIds),
위와 같이 했을 때 id가 보장되지 않는다는 문제점이 있습니다.
AcceptanceTest같은 경우 DB 테이블을 초기화하면서 autoincrement도 초기화하지만
Service의 경우 Transactioinal로 롤백하고 있기 때문에 id를 보장할 수 없습니다!

이러한 문제로 현재 코드는 일단 유지했습니다!

2022-08-03 06:26 UTC, kimchan123 approved these changes
고생하셨습니다!!!!

2022-08-03 06:26 UTC, kimchan123 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/SubmissionServiceTest.java
> +                                .containsExactly(SUBMISSION_AUTHOR_1, SUBMISSION_AUTHOR_2),
확실히 값까지 검증하니 테스트가 안정감이 있어진 것 같아요!

2022-08-04 02:07 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/TaskServiceTest.java
> +                );
```java
                        () -> assertThat(actual).hasSize(1)
                                .extracting(RunningTasksWithSectionResponse::getName)
                                .containsExactly(SECTION_NAME)
```
이 두개는 같이 묶을 수 있지 않을까요?

2022-08-04 02:15 UTC, jinyoungchoi95 approved these changes

2022-08-04 02:30 UTC, meatsby approved these changes

2022-08-04 02:35 UTC, merged