[BE] 입장코드를 해싱한다
woowacourse-teams/2022-gong-check pull request #374
Opened 2022-08-02 12:05 UTC by awesomeo184

## issue
- resolve #360 

## 코드 설명
- 기존에 Guest가 공간에 입장하기 위한 토큰을 요청하는 API에 hostId가 직접적으로 노출되던 부분을 해시값이 드러나도록 수정하였습니다. 관련 추가사항은 PR에 코멘트로 남겼습니다.

2022-08-02 12:07 UTC, awesomeo184 commented on backend/src/main/java/com/woowacourse/gongcheck/auth/application/EnterCodeProvider.java
> +
hostId -> 입장코드, 입장코드 -> hostId 로 인코딩, 디코딩하는 컴포넌트입니다.

2022-08-03 04:52 UTC, cndqjacndqja requested changes
수고하셨습니다 어썸오~ 👍

2022-08-03 04:52 UTC, cndqjacndqja commented on backend/src/main/java/com/woowacourse/gongcheck/auth/application/GuestAuthService.java
>          Host host = hostRepository.getById(hostId);
어썸오의 Long과 long의 기준이 궁금합니다!
변경되었길래 궁금해서 여쭤봐요~!

2022-08-03 04:52 UTC, cndqjacndqja commented on backend/src/main/java/com/woowacourse/gongcheck/infrastructure/hash/AES256.java
> +            // TODO: 2022/08/02 Infrastructure 예외로 변경 필요
😄

2022-08-03 04:52 UTC, cndqjacndqja commented on backend/src/main/java/com/woowacourse/gongcheck/infrastructure/hash/AES256.java
> +            throw new IllegalArgumentException(e);
외부 API에 대한 Exception은 IntrastructureException으로 던지게 될 것 같아요!
나중에 저랑 쿼리치가 로깅 PR에서 수정하겠습니다!

2022-08-03 04:52 UTC, cndqjacndqja commented on backend/src/test/java/com/woowacourse/gongcheck/infrastructure/hash/AES256Test.java
> +    }
예외 사항은 테스트하지 않아도 될까요??

2022-08-03 05:16 UTC, meatsby requested changes
수고하셨슴다!

2022-08-03 05:16 UTC, meatsby commented on backend/src/main/java/com/woowacourse/gongcheck/auth/application/EntranceCodeProvider.java
> +        if (id <= 0) {
굳이인것 같긴하지만 ㅎㅎ; 이런 식으로도 표현하면 좋을 것 같다 라는 생각 ㅎ
```suggestion
        if (id < INITIAL_ID) {
```

2022-08-03 05:16 UTC, meatsby commented on backend/src/main/java/com/woowacourse/gongcheck/core/presentation/HostController.java
> +        return ResponseEntity.ok(EntranceCodeResponse.from(hostService.createEntranceCode(hostId)));
`hostService.createEntranceCode(hostId)` 는 따로 빼는것에 대해 어떻게 생각하시나요!
개인적으론 가독성이 좀 더 좋아질 것 같아요!

2022-08-03 05:16 UTC, meatsby commented on backend/src/main/java/com/woowacourse/gongcheck/infrastructure/hash/AES256.java
> +            // TODO: 2022/08/02 Infrastructure 예외로 변경 필요
Good~!

2022-08-03 05:23 UTC, awesomeo184 commented on backend/src/main/java/com/woowacourse/gongcheck/auth/application/GuestAuthService.java
>          Host host = hostRepository.getById(hostId);
id는 모두 래퍼 클래스를 씁니다. 다만 java 11부터는 inner class에서 래퍼클래스에 대한 static 선언을 하지 못하도록 막아놔서 일부 테스트에서는 long을 사용하도록 놔두었습니다.

코멘트 주신 부분은 제가 그냥 실수로 long으로 선언한 것 같네요;

2022-08-03 05:24 UTC, awesomeo184 commented on backend/src/test/java/com/woowacourse/gongcheck/infrastructure/hash/AES256Test.java
> +    }
null에 대한 테스트를 추가할 필요가 있겠네요, 다른 예외 사항 더 있을까요?

2022-08-03 05:33 UTC, awesomeo184 commented on backend/src/main/java/com/woowacourse/gongcheck/core/presentation/HostController.java
> +        return ResponseEntity.ok(EntranceCodeResponse.from(hostService.createEntranceCode(hostId)));
반영하겠습니다

2022-08-04 01:06 UTC, kimchan123 approved these changes
고생하셨습니다!

2022-08-04 01:08 UTC, awesomeo184 commented on backend/src/main/java/com/woowacourse/gongcheck/auth/application/EntranceCodeProvider.java
> +    private final Hashable hashable;
실수네요!

2022-08-04 02:04 UTC, jinyoungchoi95 requested changes
수고하셨습니다~

몇가지 코멘트 남겨두었으니 확인 부탁드려요 :)

2022-08-04 02:04 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/infrastructure/hash/AES256Test.java
> +    }
문자열이 null이 들어오는 경우 둘다 테스트해야하지않을까요?

`aes256.encode(null);`

2022-08-04 02:29 UTC, meatsby approved these changes

2022-08-04 02:46 UTC, awesomeo184 commented on backend/src/main/java/com/woowacourse/gongcheck/auth/presentation/GuestAuthController.java
> +        Long hostId = entranceCodeProvider.parseId(entranceCode);
저도 고민했던 부분인데요. guestAuthService에게 createToken이라는 메시지를 보낼때, entranceCode를 보내는게 맞을까요, 아니면 HostId를 보내는게 맞을까요?

저도 처음에 오리가 말한대로 `EntranceCodeProvider`를 `GuestAuthService`안에 넣으려다가 멈칫하게 된 이유는 createToken이라는 메서드의 파라미터 타입이 `Long` -> `String`으로 변경되기 때문이었어요.

만약 우리가 입장코드가 아닌 다른 방식을 사용하도록 변경한다면 createToken의 퍼블릭 인터페이스가 또 변경이 될거에요. 토큰을 만드는데 필요한 정보는 hostId라는 사실은 변하지 않았는데도 불구하고요.

토큰을 만드는데 최종적으로 필요한 정보는 결국 hostId이고 , 사용자의 입력을 받아서 이를 application layer가 필요한 데이터로 변환하여 넘겨주는 것도 컨트롤러의 역할에 포함된다고 생각해서 최종적으로 이렇게 코드를 작성했어요.

@cndqjacndqja @kimchan123 @jinyoungchoi95 @meatsby 

다들 어떻게 생각하는지 한번 얘기해보면 좋을 것 같아요~

2022-08-04 04:16 UTC, awesomeo184 commented on backend/src/main/java/com/woowacourse/gongcheck/auth/presentation/GuestAuthController.java
> +        Long hostId = entranceCodeProvider.parseId(entranceCode);
https://github.com/woowacourse-teams/2022-gong-check/discussions/398

2022-08-04 04:19 UTC, cndqjacndqja approved these changes

2022-08-04 04:22 UTC, awesomeo184 commented on backend/src/test/java/com/woowacourse/gongcheck/infrastructure/hash/AES256Test.java
> +    }
테스트 추가하였습니다

2022-08-04 04:23 UTC, jinyoungchoi95 approved these changes

2022-08-04 04:31 UTC, awesomeo184 commented on backend/src/main/java/com/woowacourse/gongcheck/auth/application/Hashable.java
> +public interface Hashable {
hashTranslator로 변경하였습니당

2022-08-04 04:38 UTC, merged