[BE] 예외 Response를 세분화한다.
woowacourse-teams/2022-gong-check pull request #449
Opened 2022-08-08 13:47 UTC by meatsby

## issue
- resolve #445 

## 코드 설명
- 모든 예외를 enum 으로 분류하고 예외를 던지는 부분에서 어떤 값이 입력되었는지 로깅할 수 있도록 메시지를 수정했습니다.

### 아직 추가되지 않은 작업
- 추가적으로 valid 를 손봐야 하며, RestDocs 로 예외 enum 을 문서화 해야합니다.

2022-08-09 02:12 UTC, awesomeo184 requested changes
고생하셨어요, 코멘트 보시고 의견 달아주세요~

2022-08-09 02:12 UTC, awesomeo184 commented on backend/src/main/java/com/woowacourse/gongcheck/core/application/SpaceService.java
> +            throw new BusinessException(message, ErrorCode.SP02);
코드를 보다가 문득 든 생각인데요, 로그를 여기서 찍고 익셉션을 던질때 에러 코드만 넘긴 뒤에, 컨트롤러 어드바이스에서는 그냥 로그 안찍고 에러코드 변환만 하는게 낫지 않을까요? 그렇게하면 예외가 어디서 터진지도 추적이 가능할 것 같아서요

2022-08-09 02:12 UTC, awesomeo184 commented on backend/src/main/java/com/woowacourse/gongcheck/core/domain/submission/Submission.java
> +            throw new BusinessException(message, ErrorCode.S003);
```suggestion
            String message = String.format("제출자 이름은  %d자 이하여야 합니다. author = %s", AUTHOR_MAX_LENGTH author);
            throw new BusinessException(message, ErrorCode.S003);
```

이렇게 해도 되지 않나요??

2022-08-09 02:12 UTC, awesomeo184 commented on backend/src/main/java/com/woowacourse/gongcheck/core/domain/vo/Description.java
> +            throw new BusinessException(message, ErrorCode.D001);
여기도 정수를 파라미터로 넘길 수 있을 것 같아요

2022-08-09 09:47 UTC, cndqjacndqja commented on backend/src/main/java/com/woowacourse/gongcheck/core/application/SpaceService.java
> +            throw new BusinessException(message, ErrorCode.SP02);
예외 상황 마다 로깅을 하면, 코드 관리가 힘들 것이라 생각했어요. 로깅에 대한 코드는 여러 곳에 흝어지는 것 보다 advice 한 곳에서 관리해 주는 것이 더 좋을 것 같다는 판단이였습니다 :)

`그럼 String message는 관리할 대상이 아닌가?` 라는 질문을 스스로 해봤는데요.
예외마다 String message를 만들어 주고 있지만, 이것은 Exception에 대한 정보이지 로깅의 정보는 아니여서 저희가 advice에서 로깅 관리를 한 번에 할 때 신경써야 하는 관심사는 아니라고 판단했습니다.

2022-08-11 08:23 UTC, kimchan123 approved these changes
LGTM!

2022-08-11 12:26 UTC, jinyoungchoi95 requested changes
변경량이 많았을텐데 고생하셨습니다~

코멘트 남겨두었으니 확인부탁드려요 :)

2022-08-11 12:26 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/auth/application/EntranceCodeProvider.java
> +            throw new BusinessException(message, ErrorCode.H002);
요청이 조금 더 명확해지는거 같기는 하네요:)

2022-08-11 12:26 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/core/application/SubmissionService.java
> +                            .collect(Collectors.joining(", ")));
로깅을 위한 값이라고 보이는데요. Service에서 작업해야할 내용치고는 너무 특정 기능으로 보여요.

Util 클래스를 두고 해당 Util 클래스가 이 작업을 진행하도록 하는건 어떤가요?

2022-08-11 12:26 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/core/domain/task/RunningTasks.java
> +                    .collect(Collectors.joining(", ")));
여기두요 :)

2022-08-11 12:26 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/core/domain/vo/Name.java
> +            String message = String.format("이름은 공백일 수 없습니다. name = %s", name);
공백에 대해서도 name이 필요할까요? 공백이라면 name을 굳이 표현할 필요는 없지 않을까요?

2022-08-11 12:26 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/core/presentation/request/SectionCreateRequest.java
> +    @NotNull(message = "SectionCreateRequest 의 name은 null일 수 없습니다.")
```suggestion
    @NotNull(message = "SectionCreateRequest의 name은 null일 수 없습니다.")
```
띄어쓰기 다른곳과 다르네요

2022-08-11 12:26 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/infrastructure/oauth/GithubOauthClient.java
> +                    clientSecret, tokenUrl, profileUrl, e.getMessage());
```suggestion
                    clientId, clientSecret, tokenUrl, profileUrl, e.getMessage());
```
개행 오타가 있네요

2022-08-12 00:43 UTC, awesomeo184 approved these changes
고생하셨습니다~

2022-08-16 03:12 UTC, cndqjacndqja commented on backend/src/main/java/com/woowacourse/gongcheck/core/application/SubmissionService.java
> +                            .collect(Collectors.joining(", ")));
`Service에서 작업해야할 내용치고는 너무 특정 기능`에 대해서 저도 공감합니다!
로깅 메세지 가공(?) 작업 역할을 service가 하는 것이 저도 어색하게 느껴지는데요.

- Util클래스로 두게 되면 객체지향과는 멀어진다는 생각(객체 간의 협력이 아니라 정적 메서드를 호출하는 방식이기 때문입니다.)
- 현재 Exception 메세지 가공에 대한 역할을 Util로 두게 되면 모든 예외 사항마다 메시지가 다르기 때문에, 모든 케이스에 대한 정적 메서드가 필요하게 될 것 같습니다. (관리하기 힘들어질 것 같아요)
위 두 가지 이유를 바탕으로 Util클래스를 지양하게 되었는데요! 오리 생각은 어떤가요?

**해결 방식**
Util 클래스로 두는 것 보단 로깅 메세지 가공을 Service에서 하는 것이 아니라 다른 곳에서 하는 방식은 어떻게 생각하시나요?
매 요청에 대해 RequestSope인 빈을 생성하여 요청에 대한 body, param등의 정보를 저장합니다.
Service에서는 
throw new BusinessException("현재 제출할 수 있는 진행중인 작업이 존재하지 않습니다.", ErrorCode.S001); 만 하게 하고.
advice에서 exception.getMessage()와 정보를 저장한 빈의 값을 추출하여 로깅하는 것입니다.(이렇게 진행할 경우 slack로깅 알람에 대해서도 리팩토링 해줄 수 있겠네요!)
참고 자료입니다. [링크](https://bperhaps.tistory.com/entry/Spring-Slack-Alarm-Logger-%EB%A7%8C%EB%93%A4%EA%B8%B0)

만약 정보를 저장한 빈을 매 요청마다 생성하는 것이 불필요한 리소스 낭비 같다는 느낌이 든다면 우선 Util로 분리해보겠습니다!

2022-08-16 04:55 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/core/application/SubmissionService.java
> +                            .collect(Collectors.joining(", ")));
제가 생각하는 객체 지향은 객체간의 책임을 분리하고, 분리된 객체들을 협력시키는 관계를 구성하는데 있다라고 생각하는데요.

Util을 쓰면 정적 메소드를 호출하는 방식이 되기 때문에 객체지향에서 멀어진다라는 의견에 대해서는 동의합니다. 다만 과연 객체로써 생성해야하는 기능이냐에 대해서는 의문이 들어요.
왜냐면 이 기능은 협력을 해야하는 기능이라기보다는 "제공"만 한다에 가까운 유틸스러운 기능이거든요. 그렇다면 객체로 만들기보다는 static하게 유틸클래스로서 분리해서 사용해야한다고 생각하는데 어떻게 생각하시나요?

2022-08-16 11:49 UTC, jinyoungchoi95 requested changes
고생하셨습니다~ 빠진거있는거같아서 확인부탁드려요

2022-08-16 11:49 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/core/domain/section/SectionRepository.java
> +                .orElseThrow(() -> new NotFoundException("존재하지 않는 구역입니다.", ErrorCode.SE01));
여기도 id에 대해서 구체화해야하지 않나요?

2022-08-16 11:49 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/core/domain/task/RunningTasks.java
> +                    .collect(Collectors.joining(", ")));
여기 util로 빠지는건 다른이슈에서 처리일까요?

2022-08-16 11:52 UTC, jinyoungchoi95 approved these changes

2022-08-16 12:06 UTC, merged