[BE] updateJob 메서드에서 Job을 삭제하지 않고 수정하는 로직으로 변경한다.
woowacourse-teams/2022-gong-check pull request #457
Opened 2022-08-09 07:08 UTC by kimchan123

## issue
- resolve #451 

## 코드 설명
- Job의 이름은 수정하고 Section, Task만 지우고 재생성하는 로직으로 수정하였읍니다..

2022-08-10 00:45 UTC, cndqjacndqja requested changes
수고하셨습니다 ~ 👍

2022-08-10 00:45 UTC, cndqjacndqja commented on backend/src/main/java/com/woowacourse/gongcheck/core/application/JobService.java
> +        job.changeName(new Name(request.getName()));
request.getName()을 넘기고 job에서 생성하는 방식은 어떨까요?
Name 생성 시 예외가 발생한다면 Service보단 Job 내에서가 더 자연스러운 것 같아서요!

2022-08-10 00:45 UTC, cndqjacndqja commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +                jobService.updateJob(host.getId(), originJob.getId(), request);
혹시 이 위에 304번째 줄 `List<String> requestTaskNames;`에 private 추가해 주실 수 있을까요~?? 😆

2022-08-10 09:23 UTC, meatsby approved these changes
LGTM!

2022-08-11 05:09 UTC, awesomeo184 approved these changes
문제 없어보이네요! 고생하셨습니다 ~

2022-08-11 14:41 UTC, kimchan123 commented on backend/src/main/java/com/woowacourse/gongcheck/core/application/JobService.java
> +        job.changeName(new Name(request.getName()));
changeName의 파라미터가 String보단 Name인게 타입 안정성이 높아질거라 생각했어요! name의 자료형이 String에서 바뀔일은 없을 것 같긴한데...

2022-08-11 14:43 UTC, kimchan123 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/JobServiceTest.java
> +                jobService.updateJob(host.getId(), originJob.getId(), request);
반영했습니다!

2022-08-11 14:44 UTC, merged