[BE] @Valid 보다 @HostOnly 가 먼저 동작하도록 한다.
woowacourse-teams/2022-gong-check pull request #476
Opened 2022-08-10 08:13 UTC by jinyoungchoi95

## issue
- resolve #247

## 코드 설명
- aop를 제거하고 인가 관련 로직을 interceptor에서 진행할 수 있도록 수정하였습니다.
- Mocking처리 관련해서 의미없는 모킹처리들이 너무 많아서 차후 리팩토링이 필요할 것 같네요.

2022-08-10 09:44 UTC, meatsby requested changes
수고하셨습니당

2022-08-10 09:44 UTC, meatsby commented on backend/src/main/java/com/woowacourse/gongcheck/auth/presentation/AuthenticationInterceptor.java
> +    private void checkAuthorize(Authority authority) {
authorize 혹은 checkAuthority 로 변경하는건 어떨까요!

+ final 도 추가해주세요!

2022-08-10 09:44 UTC, meatsby commented on backend/src/main/java/com/woowacourse/gongcheck/auth/presentation/AuthenticationInterceptor.java
> -        authenticationContext.setAuthority(authority);
AuthenticationContext 에 이제 authority 필드가 불필요하지 않을까요?

2022-08-11 05:19 UTC, awesomeo184 requested changes
고생하셨습니다. 코멘트 하나 남겼어요~ 확인 부탁드려요~

2022-08-11 05:19 UTC, awesomeo184 commented on backend/src/main/java/com/woowacourse/gongcheck/auth/presentation/AuthenticationInterceptor.java
> +
무엇이 NotAnnotated인지 보려면 private 메서드를 확인해야될 것 같아요. 메서드 이름에 명시를해주는 것이 좋지않을까요>?

2022-08-11 12:52 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/auth/presentation/AuthenticationInterceptor.java
> -        authenticationContext.setAuthority(authority);
그렇네요..

2022-08-11 15:23 UTC, cndqjacndqja approved these changes
Interceptor에서 인증 인가 후에, `@HostOnly` 관련 로직이 메서드 호출 관련 시점에서 실행되는 것이 어색했는데, AOP 제거 후 이것을 Interceptor로 옮겨 주셨군요!(제가 이해한 것이 맞을까요?) 

코드를 보다 보니, 저희 프로젝트는 Host용 API와 Guest용 API가 분리되는 것이 어떨까 생각이 드네요..! 
비즈니스 로직은 공통되는 부분이 있지만, API호출이나 인증 인가 관련한 로직은 서로 독립적이여도 괜찮을 것 같다는 것이 이유입니다! (회의 때 다시 한번 의견 제시해보겠습니다 ☺️)

추가 요청 사항
- AuthenticationPrincipalArgumentResolver.class에 resolveArgument() 메서드에서 `throws Exception` 제거 가능할까요??

2022-08-11 15:27 UTC, kimchan123 approved these changes
고생하셨습니다! 가라로 처리하셨다고 했는데 어느 부분에서 그렇게 말씀하신건지 궁금해요~!

2022-08-12 00:41 UTC, awesomeo184 approved these changes
고생하셨습니다~

2022-08-12 01:49 UTC, jinyoungchoi95 commented
> Interceptor에서 인증 인가 후에, `@HostOnly` 관련 로직이 메서드 호출 관련 시점에서 실행되는 것이 어색했는데, AOP 제거 후 이것을 Interceptor로 옮겨 주셨군요!(제가 이해한 것이 맞을까요?)
> 
> 코드를 보다 보니, 저희 프로젝트는 Host용 API와 Guest용 API가 분리되는 것이 어떨까 생각이 드네요..! 비즈니스 로직은 공통되는 부분이 있지만, API호출이나 인증 인가 관련한 로직은 서로 독립적이여도 괜찮을 것 같다는 것이 이유입니다! (회의 때 다시 한번 의견 제시해보겠습니다 ☺️)
> 
> 추가 요청 사항
> 
> * AuthenticationPrincipalArgumentResolver.class에 resolveArgument() 메서드에서 `throws Exception` 제거 가능할까요??

제거하였습니다~

2022-08-12 01:54 UTC, jinyoungchoi95 commented
> 고생하셨습니다! 가라로 처리하셨다고 했는데 어느 부분에서 그렇게 말씀하신건지 궁금해요~!

현재 구조상 각각의 controller 메소드에 `@HostOnly`를 달아두고 해당 메소드를 인가처리하고있는데요.
원래 목표했던 방향은 Interceptor에서 path를 등록할 때 인가와 메소드를 전부다 같이 넣어서 해당 객체에서 필터링을 진행하려고 했어요. 현재와 같은 구조라면 어떤 api가 권한이 걸려있는지 파악하기 힘드니까요.

구조를 생각하는데 시간 한계상 현재와 같이 구현은 해두었고 차후 수정해보겠습니다 :)

2022-08-12 01:58 UTC, meatsby approved these changes
수고하셨습니당~

2022-08-12 02:09 UTC, merged