[BE] 해당 Section의 모든 runningTask를 체크하는 기능을 구현한다.
woowacourse-teams/2022-gong-check pull request #480
Opened 2022-08-11 05:02 UTC by kimchan123

## issue
- resolve #479 

## 코드 설명
- HostId와 SectionId를 받아 해당 Section의 모든 runningTask를 체크하는 기능을 구현했습니다.
- 동일한 로직의 반복이라 이해하기 어려운 부분은 없으실 것 같아요!

2022-08-11 12:42 UTC, jinyoungchoi95 requested changes
수고하셨습니다~

코멘트 확인 부탁드려요 :)

2022-08-11 12:42 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/core/domain/task/RunningTasks.java
> +    public void check() {
```suggestion
    public void AllCheck() {
```
모두 체크한다라는 의미가 더 명확할 것 같네요 :)

2022-08-11 12:42 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/SupportRepository.java
> +        return entityManager.createQuery(String.format("SELECT entity FROM %s entity", className)).getResultList();
```suggestion
        return entityManager.createQuery(String.format("SELECT entity FROM %s entity", className))
            .getResultList();
```
개행 확인해주세요~

2022-08-11 15:59 UTC, cndqjacndqja requested changes
고생하셨습니다 ~ 👍 
추가적으로 테스트 관련 코멘트 봐주시면 좋을 것 같아요!

2022-08-11 15:59 UTC, cndqjacndqja commented on backend/src/main/java/com/woowacourse/gongcheck/core/application/TaskService.java
> +        runningTasks.check();
혹시 Tasks에 메세지를 보내는 방식은 어떨까요?? :)

2022-08-11 15:59 UTC, cndqjacndqja commented on backend/src/main/java/com/woowacourse/gongcheck/core/domain/task/RunningTasks.java
> +    public void check() {
오리의 의견에 동의합니당 :)

2022-08-11 15:59 UTC, cndqjacndqja commented on backend/src/test/java/com/woowacourse/gongcheck/core/domain/section/SectionRepositoryTest.java
> +                assertThat(result).hasSize(3);
혹시 size검증 외에도 값이 제대로 조회됐는지 추가해주실 수 있을까요~? 😄
지난 번 리팩토링 작업 때 수정했던게 생각나서요!

2022-08-12 00:57 UTC, awesomeo184 approved these changes
고생하셨습니다~ 오리 코멘트에 추가의견 남겼어요~

2022-08-12 00:57 UTC, awesomeo184 commented on backend/src/main/java/com/woowacourse/gongcheck/core/domain/task/RunningTasks.java
> +    public void check() {
할거라면 checkAll이 더 좋을 것 같아요

2022-08-12 00:57 UTC, awesomeo184 commented on backend/src/test/java/com/woowacourse/gongcheck/acceptance/TaskAcceptanceTest.java
> +    }
👍

2022-08-12 00:57 UTC, awesomeo184 commented on backend/src/main/java/com/woowacourse/gongcheck/core/application/TaskService.java
>          }
나중에 로깅과 예외코드 응답 추가하는 것 잊으면 안 되겠네요

2022-08-12 01:48 UTC, kimchan123 commented on backend/src/main/java/com/woowacourse/gongcheck/core/domain/task/RunningTasks.java
> +    public void check() {
checkAll로 하겠습니다~!

2022-08-12 02:11 UTC, jinyoungchoi95 approved these changes

2022-08-12 05:46 UTC, meatsby requested changes

2022-08-12 05:46 UTC, meatsby commented on backend/src/main/java/com/woowacourse/gongcheck/core/domain/task/RunningTask.java
> +    }
올체크 버튼을 누르면 항상 올체크만 가능하겠네요.
올체크를 누르고 다시 모두 체크를 해제하기 위해선 하나하나 모두 언체크를 해줘야하는 작업이 생길 것 같은데, 올체크와 올언체크를 모두 만드는 것은 어떨까요?

2022-08-12 05:46 UTC, meatsby commented on backend/src/main/java/com/woowacourse/gongcheck/core/domain/task/TaskRepository.java
> +    List<Task> findAllBySection(Section section);
```suggestion
    List<Task> findAllBySection(final Section section);
```

2022-08-12 05:46 UTC, meatsby commented on backend/src/main/java/com/woowacourse/gongcheck/core/presentation/TaskController.java
> +    @PostMapping("/sections/{sectionId}/runningTasks/check")
```suggestion
    @PostMapping("/sections/{sectionId}/runningTasks/allCheck")
```
이건 어떨까요?

2022-08-12 05:46 UTC, meatsby commented on backend/src/test/java/com/woowacourse/gongcheck/core/domain/task/RunningTasksTest.java
> +        RunningTask runningTask2 = RunningTask_생성(2L, false);
하나는 false, 하나는 true 인 상황도 고려해보면 좋을 것 같아요!

2022-08-12 15:04 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/core/domain/task/RunningTask.java
> +    }
이거는 구현내용이 추가되었을때 진행하면 좋을 것 같아요 :)

2022-08-16 02:48 UTC, meatsby approved these changes
수고하셨습니다!

2022-08-16 03:16 UTC, cndqjacndqja approved these changes

2022-08-16 04:33 UTC, merged