[BE] 인수테스트에 cucumber를 적용하기 위한 환경을 설정한다.
woowacourse-teams/2022-gong-check pull request #485
Opened 2022-08-12 05:23 UTC by awesomeo184

## issue
- resolve #184 

## 코드 설명

기본적인 환경 설정과 시나리오 코드 예시 하나를 추가했습니다.

### 이전에 cucumber task가 동작하지 않았던 이유.

저번에 함께 트러블슈팅을 할 때, H2 드라이버를 찾아올 수 없다는 에러가 발생했었는데요, 알고보니 큐컴버를 위한 클래스패스 설정에서 `runtimeOnly` 의존성이 설정이 안되어 있어서 그랬습니다.

아래와 같이 런타임 의존성도 패스에 추가하여 문제를 해결했습니다.

```groovy
configurations {
    cucumberRuntime.extendsFrom(implementation, testImplementation, runtimeOnly)
}

...
task acceptanceTest() {
    dependsOn assemble, compileTestJava
    doLast {
        javaexec {
            main = "io.cucumber.core.cli.Main"
            classpath = configurations.cucumberRuntime + sourceSets.main.output + sourceSets.test.output
            args = [
                    '--plugin', 'pretty',
                    '--plugin', 'html:build/reports/cucumber/cucumber-report.html',
                    '--glue', 'com.woowacourse.gongcheck',
                    'src/test/resources/features']
        }
    }
}
```

### 빌드시 큐컴버 태스크가 돌아가지 않는 문제.

gradle에 `check`라는 task가 있습니다. 여기 해당 태스크를 추가하면 빌드할 때 함께 돌아갑니다. `build`는 `check`에 의존하고 있습니다.

관련 문서: https://docs.gradle.org/current/userguide/base_plugin.html#sec:base_tasks

### 기본 설정

`CucumberIntegrationTest`: 인수테스트를 할 때, 스프링 설정과 큐컴버 설정을 읽어오는 부트스트랩 클래스입니다.

`AcceptanceContext`: 큐컴버로 테스트를 작성할 때, Given, When, Then을 각각 다른 메서드로 정의합니다. 이때 다른 메서드에서 상태(ex. `io.restassured.response.Response`)를 공유할 수 있도록 전역적으로 상태를 관리하는 객체가 하나 필요합니다. 매 시나리오마다 새로 생성됩니다.

`AcceptanceStep`: StepDefinition을 작성할 때는 이 클래스를 상속받아 context를 통해 요청을 보내고 응답을 꺼내오면 됩니다.

## 개선사항

현재 `CucumberIntegrationTest`에 `@ActiveProfiles("test")`를 붙이지 않으면 빌드할 때 local 설정을 읽어오는 문제가 있습니다. 차후 원인을 찾아보고 수정하도록 하겠습니다. 일단 `@ActiveProfiles("test")`를 붙이면 빌드할 때 test 설정을 읽어옵니다.

현재 존재하는 AcceptanceTest 코드를 모두 Cucumber로 마이그레이션 하면 `CucumberIntegrationTest` -> `AcceptanceTest`로 이름을 수정하도록 하겠습니다.

2022-08-12 05:55 UTC, meatsby requested changes

2022-08-12 05:55 UTC, meatsby commented on backend/src/test/resources/features/guestAuth.feature
> +    Then 엑세스 토큰을 받는다
databaseInitializer 를 제거하고 이제 given 이 추가되면 되는건가요?

2022-08-12 05:55 UTC, meatsby commented on backend/src/test/java/com/woowacourse/gongcheck/cucumber/steps/GuestAuthStepDefinitions.java
> +                        context.response.body().jsonPath().getObject(".", GuestTokenResponse.class)).isNotNull()
개행이 좀 더 예쁘면 좋을 것 같아요!

2022-08-16 02:53 UTC, kimchan123 approved these changes
어썸오가 고생해서 적용한 cucumber 덕분에 인수테스트가 깔끔해질 수 있을 것 같아요~!👍

2022-08-16 03:15 UTC, jinyoungchoi95 requested changes
수고하셨습니다~

코맨트 확인부탁드려요:)

2022-08-16 03:15 UTC, jinyoungchoi95 commented on backend/build.gradle
> +    testImplementation 'io.cucumber:cucumber-junit-platform-engine:6.10.4'
`6.10.4`라는 버전을 공통적으로 사용하고 있는데요. 공통적으로 사용하는 변수이니만큼 똑같은 변수를 하드코딩했을때의 휴먼이슈가 발생할 수 있다라고 생각해요 (상수를 쓰는 이유처럼요)
따라서 상수처럼 gradle을 사용할 수 있도록 변경해보면 어떨까 싶어요 :)

```groovy
ext {
    cucumberVersion = '6.10.4'
}

dependencies {
    // ...
    testImplementation 'io.cucumber:cucumber-java:$cucumberVersion'
    testImplementation 'io.cucumber:cucumber-spring:$cucumberVersion'
    testImplementation 'io.cucumber:cucumber-junit-platform-engine:$cucumberVersion'
}
```
https://stackoverflow.com/questions/38106576/how-do-i-define-a-variable-for-the-dependency-version-in-gradle

2022-08-16 03:15 UTC, jinyoungchoi95 commented on backend/build.gradle
> +}
```suggestion
check {
    dependsOn cucumber
}
```
통일성있게 문법을 사용하는 것도 좋을 것 같네요
 
build에 의존해도 되는거같은데 왜 check에 의존하고 있는지 설명가능할까요?

2022-08-16 03:15 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/cucumber/AcceptanceContext.java
> +
의미없는 한줄로 보이네요~

2022-08-16 03:15 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/cucumber/AcceptanceSteps.java
> +
여기도 마찬가지입니다

2022-08-16 03:15 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/cucumber/AcceptanceContext.java
> +@Scope(scopeName = "cucumber-glue")
scope name은 cucumber 지정스펙인가용?

2022-08-16 03:15 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/cucumber/AcceptanceContext.java
> +    public void invokeHttpPost(String path, Object data) {
post말고 추가적으로 더 필요하다면 해당 클래스에서 추가하면 되는부분일까요?

2022-08-16 03:15 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/cucumber/AcceptanceContext.java
> +                .body(data).contentType(ContentType.JSON);
```suggestion
                .body(data)
                .contentType(ContentType.JSON);
```

2022-08-16 03:15 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/cucumber/steps/GuestAuthStepDefinitions.java
> +    }
데이터 입력은 차후 이야기해야할 것 같네요~

2022-08-16 03:15 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/cucumber/steps/GuestAuthStepDefinitions.java
> +    @When("Space의 패스워드를 입력하면")
패스워드에 대한 값을 입력받으면 어떨까요?

`Space의 패스워드에 1234를 입력하면`

2022-08-16 03:16 UTC, awesomeo184 commented on backend/build.gradle
> +    testImplementation 'io.cucumber:cucumber-junit-platform-engine:6.10.4'
좋은 의견이네요~ 반영하도록 할게요

2022-08-16 04:25 UTC, awesomeo184 commented on backend/src/test/resources/features/guestAuth.feature
> +    Then 엑세스 토큰을 받는다
네 아마 그렇게 구성해야될듯

2022-08-16 04:28 UTC, awesomeo184 commented on backend/src/test/java/com/woowacourse/gongcheck/cucumber/steps/GuestAuthStepDefinitions.java
> +                        context.response.body().jsonPath().getObject(".", GuestTokenResponse.class)).isNotNull()
어떻게 할까요?

2022-08-16 04:40 UTC, awesomeo184 commented on backend/src/test/java/com/woowacourse/gongcheck/cucumber/AcceptanceContext.java
> +@Scope(scopeName = "cucumber-glue")
넵 glue는 cucumber에서 하나의 StepDefinition (ex. `GuestAuthStepDefinitions`)을 의미하고 해당 스코프 등록은 라이브러리에 이미 되어 있습니다.

2022-08-16 04:40 UTC, awesomeo184 commented on backend/src/test/java/com/woowacourse/gongcheck/cucumber/AcceptanceContext.java
> +    public void invokeHttpPost(String path, Object data) {
넵

2022-08-16 04:48 UTC, awesomeo184 commented on backend/src/test/java/com/woowacourse/gongcheck/cucumber/steps/GuestAuthStepDefinitions.java
> +    @When("Space의 패스워드를 입력하면")
이렇게 작성하려면 공간 비밀번호를 1234로 등록한다는 작업도 시나리오에 들어가야 자연스러울 것 같은데 차후에 변경해보도록 하겠습니다!

2022-08-16 04:49 UTC, awesomeo184 commented on backend/build.gradle
> +}
https://www.baeldung.com/gradle-test-vs-check#check-task

저희 상황에서는 굳이 check가 의존하도록 하지 않아도 될 것 같아요. build로 수정하겠습니다.

2022-08-16 04:50 UTC, awesomeo184 commented on backend/build.gradle
> +    testImplementation 'io.cucumber:cucumber-junit-platform-engine:6.10.4'
적용해봤는데, 라이브러리를 못찾아오네요. 지금 당장은 문제를 못찾겠어요 ㅠ. 버전 상수를 쓰는 부분이 여기 말고도 많아서 나중에 한번에 리팩터링 하는것이 좋을 것 같아요

2022-08-16 06:42 UTC, meatsby approved these changes

2022-08-16 06:42 UTC, meatsby commented on backend/src/test/java/com/woowacourse/gongcheck/cucumber/steps/GuestAuthStepDefinitions.java
> +                        context.response.body().jsonPath().getObject(".", GuestTokenResponse.class)).isNotNull()
```suggestion
                () -> assertThat(context.response.body().jsonPath().getObject(".", GuestTokenResponse.class))
                        .isNotNull()
```
요런 느낌~?

2022-08-16 07:42 UTC, jinyoungchoi95 commented on backend/build.gradle
> +    testImplementation 'io.cucumber:cucumber-junit-platform-engine:6.10.4'
ㅋㅋㅋ넵 알겠습니다

2022-08-16 08:59 UTC, cndqjacndqja approved these changes
고생하셨습니다 ~ 👍

2022-08-16 10:43 UTC, awesomeo184 commented on backend/src/test/java/com/woowacourse/gongcheck/cucumber/steps/GuestAuthStepDefinitions.java
> +                        context.response.body().jsonPath().getObject(".", GuestTokenResponse.class)).isNotNull()
더 이상해요

2022-08-16 11:53 UTC, jinyoungchoi95 approved these changes

2022-08-16 11:54 UTC, merged