[BE] SonarCloud에서 SonarQube로 전환한다.
woowacourse-teams/2022-gong-check pull request #492
Opened 2022-08-14 16:08 UTC by cndqjacndqja

## issue
- resolve #491 

## 코드 설명
- 기존의 sonarcloude를 제거한 후, sonarqube로 전환했습니다.
- 자세한 설정 과정과 설명은 링크로 추가하겠습니다.

2022-08-16 04:36 UTC, kimchan123 approved these changes
애증의 소나큐브... 고생하셨습니다!

2022-08-16 07:46 UTC, jinyoungchoi95 approved these changes
수고하셨습니다~

2022-08-16 07:46 UTC, jinyoungchoi95 commented on backend/build.gradle
> +    id "org.sonarqube" version "3.2.0"
버전 내린 이유가 있을까요?

2022-08-16 07:46 UTC, jinyoungchoi95 commented on backend/build.gradle
> -        property 'sonar.language', 'java'
왜사라진건가요 👀

2022-08-16 08:52 UTC, cndqjacndqja commented on backend/build.gradle
> +    id "org.sonarqube" version "3.2.0"
sonarqube에서 LTS 버전이 8.9라서 낮췄습니다 :)

2022-08-16 11:59 UTC, jinyoungchoi95 requested changes

2022-08-16 11:59 UTC, jinyoungchoi95 commented on .github/workflows/backend.yml
> +    types: [ opened, synchronize, reopened ]
이거 기존에서 띄운이유가 있을까요?
다른 yml들은 안띄워져있어서 포맷을 맞추어야할거같네요

2022-08-17 01:05 UTC, cndqjacndqja commented on backend/build.gradle
> -        property 'sonar.language', 'java'
제가 이해한대로는
- `sonar.host.url`는 secretKey에 SONARQUBE_HOST_URL로 존재하여 backend.yml에서 추가해줬습니다.
- `sonar.coverage.jacoco.xmlReportPaths` [링크](https://docs.sonarqube.org/latest/analysis/test-coverage/java-test-coverage/)에서 `The SonarQube plugin automatically detects this location so no further configuration is required.`를 보고 지정해주지 않아도 sonarqube가 감지할 수 있다는 것으로 이해하여 제거했습니다.
- `sonar.organization, sonar.language`은 sonarqube web에서 지정해주기 때문에 따로 설정을 추가해주지 않아도 되는 것으로 이해했습니다.

2022-08-17 01:21 UTC, awesomeo184 approved these changes
고생 많으셨습니다~

2022-08-17 01:56 UTC, jinyoungchoi95 approved these changes

2022-08-17 02:29 UTC, meatsby approved these changes
고생하셨슴다

2022-08-17 03:52 UTC, merged