[BE] HostServiceTest와 SpaceServiceTest를 개선한다
woowacourse-teams/2022-gong-check pull request #521
Opened 2022-08-17 14:33 UTC by awesomeo184

## issue
- resolve #517 

## 코드 설명

HostService와 SpaceServiceTest의 가독성을 개선해보았습니다. 

## 변경점

### Setup 메서드에서 초기화하던 것을 변수 선언에서 한번에 처리했습니다.
 
선언과 초기화가 분리되어 있다보니 해당 변수가 어떻게 초기화 되어있는지 확인하는 과정이 번거롭다고 판단했기 때문입니다. Context 부분은 테스트할 메서드의 입력 파라미터를 설명하는 것이 주 목적인데, 선언과 할당을 같이 하는 것이 이 목적을 더 잘 달성한다고 생각했습니다.

### 중복되는 Context는 abstract context를 선언하여 재사용하는 방식으로 구성했습니다.

### 해피케이스의 Context를 단순화하였습니다.

예를들어, changeSpace 메서드의 해피케이스는, `입력받은 Host가 존재하고 입력받은 Space가 입력받은 Host의 소유이며, 입력받은 ChangeSpaceRequest의 name이 기존에 있던 Space와 중복되지 않는 경우`입니다.

이를 Context에서 자세하게 서술하는 것은 불가능하다고 생각합니다. 또 이를 단순화하여 `존재하는 Host와 존재하는 Space를 입력받는 경우`라고 서술하면, 해피케이스의 Context를 불완전하게 전달하여 코드를 읽는 사람에게 잘못된 정보를 줄 수 있다고 생각합니다. 따라서 언해피 케이스는 다른 예외 Context에서 설명하고 해피케이스는 단순히 `올바른 입력을 받는 경우`라고 서술하였습니다.

---

이후 다른 서비스 테스트를 리팩토링하기 전에 샘플용으로 팀원들의 의견을 받아보고자 먼저 PR 날려봅니다.

추가적으로 
* SpaceService의 changeSpace 메서드의 테스트가 누락된 것을 발견하여 추가했습니다.
* SpaceService의 메서드 순서를 테스트 순서와 일관되도록 정렬하였습니다.

2022-08-18 02:12 UTC, kimchan123 approved these changes
지금은 space라 depth가 적어 큰 변화가 없어보이는데 확실히 runningTask와 같이 깊은 depth에선 반복적으로 생성되는 부분을 제거할 수 있겠네요!

2022-08-18 02:12 UTC, kimchan123 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/SpaceServiceTest.java
>              void setUp() {
아직 setUp이 남아있네요!

2022-08-18 04:21 UTC, meatsby requested changes
수고하셨슴당

2022-08-18 04:21 UTC, meatsby commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/SpaceServiceTest.java
> +                repository.save(Space_생성(host, SPACE_NAME));
여기는 setUp 을 유지한 이유가 있으신가요?

2022-08-18 04:21 UTC, meatsby commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/HostServiceTest.java
> +                assertThatThrownBy(() -> hostService.createEntranceCode(1L))
지금 Context 엔 호스트가 생성되어있진 않지만, 명시적으로 없는 호스트를 표현해주기 위해선 0L 로 표현하는게 좋을 것 같아요! + 위처럼 `private static final long NON_EXIST_HOST_ID = 0L;` 상수로 표현해주면 더 좋을 것 같아요!

2022-08-18 04:21 UTC, meatsby commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/SpaceServiceTest.java
> +            private final Host host = repository.save(Host_생성("1234", 1234L));
이런 경우엔 Host 가 있는 경우 라는 메서드 혹은 상수로 빼지 않으신 이유가 있으신가요?

2022-08-18 05:38 UTC, cndqjacndqja requested changes
수고하셨습니다 👍 
추가로 코멘트 달아놨습니다 :)

2022-09-13 11:15 UTC, jinyoungchoi95 approved these changes

2022-09-14 03:36 UTC, meatsby approved these changes

2022-09-14 06:21 UTC, cndqjacndqja approved these changes

2022-09-14 06:21 UTC, merged