[BE] 이미지 반환 시 webp 확장자로 반환할 수 있도록 전환한다.
woowacourse-teams/2022-gong-check pull request #523
Opened 2022-08-18 05:38 UTC by jinyoungchoi95

## issue
- resolve #495

## 코드 설명
- #495 이슈에서 이야기한 이미지 반환 시 webp의 형태로 반환할 수 있도록 수정하는 feature입니다.

### api 정보
full api : `GET /api/resize/{imageUrl}?webp=true&width=500`
- web
    - webp로의 전환 여부입니다.
    - webp를 사용하고 싶다면 true, 기존 확장자를 사용하고 싶다면 false이며 값이 없을 시 default는 true입니다.
- width
    - width resize 배율입니다. width기준으로 배율을 맞추어 height도 수정됩니다.
    - default : 500

### dependency
- 기존의 미사용 dependency의 경우 모두 제거하였습니다.
- `implementation 'com.sksamuel.scrimage:scrimage-core:4.0.31'`는 리사이징을 최적화하기 위함입니다.

### webp
- 이전 이슈에서 이야기가 나왔던 webp 라이브러리의 경우 저희 인스턴스에 사용하는 linux arm에서는 호환이 되지 않습니다
- 바이너리파일 자체가 linux 86 64에 대해서만 라이브러리가 호환을 하고 있기 때문에 liniux arm에서는 동작하지 않으므로 해당 바이너리 파일을 통한 구현체를 새로 생성한 상태입니다.
- 아래는 각각의 webp관련된 로직에 대한 구현체들입니다.

### Convert2WebpStrategy
- convert 하기 위한 strategy 인터페이스입니다.

### WebpHandler
- webp관련된 바이너리 파일을 읽어서 사용할 수 있도록 세팅하기 위한 최상위 추상 클래스 입니다.
- `installBinary()`에서 tmp 저장소에 build된 바이너리파일을 읽어서 저장합니다. 차후 webp 사용시 쓰이는 바이너리파일이 저장된 각각의 파일에 해당합니다.

### CwebpHandler, Gif2WebpHandler
- cweb, gif2webp 바이너리를 통해 convert해주는 클래스입니다.
- cweb의 경우 정적인 파일 gif2webp의 경우 animated gif를 위함이며 서로 호환되는 곳이 달라 구분지어져있습니다.

```java
public byte[] convert(byte[] bytes) throws IOException {
    Path source = Files.createTempFile("input", "gif").toAbsolutePath();
    Path target = Files.createTempFile("to_webp", "webp").toAbsolutePath();
    try {
        Files.write(source, bytes, StandardOpenOption.CREATE);
        convert(source, target);
        return Files.readAllBytes(target);
    } finally {
        source.toFile()
                .delete();
        target.toFile()
                .delete();
    }
}
```
- `source`는 원본 파일을 임시로 저장하기 위함, `target`은 webp로 전환된 파일을 저장하기 위함이며 각각의 파일을 사용하고 `target`에서 byte값만 빼내온 후 삭제합니다.

```java
private void convert(Path source, Path target) throws IOException {
    Path stdout = Files.createTempFile("stdout", "webp");
    List<String> commands = new ArrayList<>();
    commands.add(binary.toAbsolutePath().toString());
    commands.add(source.toAbsolutePath().toString());
    commands.add("-o");
    commands.add(target.toAbsolutePath().toString());

    ProcessBuilder builder = new ProcessBuilder(commands);
    builder.redirectErrorStream(true);
    builder.redirectOutput(stdout.toFile());

    Process process = builder.start();
    try {
        process.waitFor(5, TimeUnit.MINUTES);
    } catch (InterruptedException e) {
        throw new IOException(e);
    }
    int exitStatus = process.exitValue();
    if (exitStatus != 0) {
        List<String> error = Files.readAllLines(stdout);
        throw new IOException(error.toString());
    }
}
```
- 바이너리파일을 가지고 converting을 실제로 동작시키는 메소드입니다.
- `stdouot`의 경우 실행 후의 에러 정보를 담기 위한 파일입니다. (라이브러리에서 구현된 구현체정보를 참고해서 작성하였는데 stdout도 위와 마찬가지로 delete하는 과정을 거쳐야하지 않나 싶네요. tmp에 저장되기 때문에 오래 남아있는 파일은 아닙니다)
- commands를 전부 작성하고 해당 commands를 os별로 실행시키는 과정입니다. command를 process하면 아래와 같은 구문이 진행된다라고 보면 될 것 같네요
```command
<바이너리 파일> <변경전 파일 ex).gif> -o <변경할 파일 ex).webp>
```

2022-08-18 06:57 UTC, awesomeo184 requested changes
고생많으셨습니다~ 코멘트 몇개 남겼어요

2022-08-18 06:57 UTC, awesomeo184 commented on imagestorage/src/test/java/com/woowacourse/imagestorage/application/ImageServiceTest.java
> +        class 반환할_이미지의_경로와_변경할_이미지_가로길이와_webp변환확인을_입력받은_경우 {
테스트 이름 길이 줄여야겠네요.
```
/Users/awesomeo184/woowacourse/project/2022-gong-check/imagestorage/build/test-results/test/TEST-com.woowacourse.imagestorage.application.ImageServiceTest$getResizeImage_#ba54#c18c#b4dc#b294$#bc18#d658#d560_#c774#bbf8#c9c0#c758_#acbd#b85c#c640_#bcc0#acbd#d560_#c774#bbf8#c9c0_#ac00#b85c#ae38#c774#c640_webp#bcc0#d658#d655#c778#c744_#c785#b825#bc1b#c740_#acbd#c6b0.xml (File name too long)
```

2022-08-18 06:57 UTC, awesomeo184 commented on imagestorage/src/test/java/com/woowacourse/imagestorage/application/ImageServiceTest.java
> +        class 반환할_이미지의_경로와_변경할_이미지_가로길이와_webp변환불가를_입력받은_경우 {
여기도 줄여야겠네요

2022-08-18 06:57 UTC, awesomeo184 commented on imagestorage/src/test/java/com/woowacourse/imagestorage/application/ImageServiceTest.java
>              }
테스트 이름을 고쳐야할 것 같아요! `isWebp = false` 인 경우라서요

2022-08-18 06:57 UTC, awesomeo184 commented on imagestorage/src/main/java/com/woowacourse/imagestorage/domain/ImageExtension.java
> +    GIF("gif", MediaType.IMAGE_GIF, new GifImageResizeStrategy(), new Gif2WebpStrategy()),
SVG 파일의 경우 JpegWriter로 write해도 문제가 없나요?

2022-08-18 06:57 UTC, awesomeo184 commented on imagestorage/src/main/java/com/woowacourse/imagestorage/strategy/convert/Gif2WebpStrategy.java
> +        try {
`@Override` 달아주세용

2022-08-18 06:57 UTC, awesomeo184 commented on imagestorage/src/main/java/com/woowacourse/imagestorage/strategy/convert/handler/Gif2WebpHandler.java
> +        commands.add(target.toAbsolutePath().toString());
이 코드는 CwebpHandler와 완전히 중복되는데요, `WebpHandler`에 두지 않고 하위 구현체에 따로 배치한 이유가 있을까요?

2022-08-18 07:30 UTC, kimchan123 approved these changes
L so GTM!

2022-08-18 07:30 UTC, kimchan123 commented on imagestorage/src/main/java/com/woowacourse/imagestorage/strategy/convert/Gif2WebpStrategy.java
> +    private static final Gif2WebpHandler DEFAULT = new Gif2WebpHandler();
이부분을 static final로 빼는 이유가 있나요?

2022-08-18 07:34 UTC, meatsby approved these changes
어렵네요.. ㅎㅎ 나중에 세미나 한 번 해주시죠

2022-08-18 07:34 UTC, meatsby commented on imagestorage/src/main/java/com/woowacourse/imagestorage/application/ImageService.java
> +                return ImageResponse.of(imageExtension.convertToWebp(resizedImage), new MediaType("image", "webp"));
`new MediaType("image", "webp")` 상수로 빼주시던지 아니면 스프링 미디어타입 컨트리뷰션 하십쇼!

2022-08-18 07:34 UTC, meatsby commented on imagestorage/src/main/java/com/woowacourse/imagestorage/strategy/convert/handler/CwebpHandler.java
> +public class CwebpHandler extends WebpHandler {
왜 Cwebp 인가요?

2022-08-18 07:34 UTC, meatsby commented on imagestorage/src/main/java/com/woowacourse/imagestorage/strategy/convert/handler/Gif2WebpHandler.java
> +    }
이 로직은 왜 필요한가요..?

2022-08-18 07:45 UTC, cndqjacndqja requested changes
고생 많으셨습니다 👍 
추가로 ErrorCode 관련해서는 아직 작성하지 않은 것 같은데요!
혹시 이 부분도 추가해 주실 수 있을까요~?

2022-08-18 07:45 UTC, cndqjacndqja commented on imagestorage/src/main/java/com/woowacourse/imagestorage/strategy/convert/handler/CwebpHandler.java
> +            process.waitFor(5, TimeUnit.MINUTES);
혹시 이 부분은 왜 필요한 것일까요??

2022-08-18 07:45 UTC, cndqjacndqja commented on imagestorage/src/main/java/com/woowacourse/imagestorage/strategy/convert/handler/CwebpHandler.java
> +        if (exitStatus != 0) {
메서드나 상수로 분리하면 더 이해하기 쉬울 것 같아요!

2022-08-18 07:45 UTC, cndqjacndqja commented on imagestorage/src/main/java/com/woowacourse/imagestorage/strategy/convert/handler/Gif2WebpHandler.java
> +        Path stdout = Files.createTempFile("stdout", "webp");
중복 코드로 sonarqube에서 code smell이 잡힐 것 같네요!
Gif2WebpHandler, CwebpHandler 두 곳에서 사용하고 있는데, 중복을 제거해 보는 것은 어떨까요?

2022-08-18 07:45 UTC, cndqjacndqja commented on imagestorage/src/main/java/com/woowacourse/imagestorage/strategy/convert/handler/WebpHandler.java
> +                    .waitFor(30, TimeUnit.SECONDS);
waitFor과 같은 로직들이 보이는데, 혹시 어떤 이유 때문에 필요한 것일까요??

2022-08-18 07:45 UTC, cndqjacndqja commented on imagestorage/src/test/java/com/woowacourse/imagestorage/ImageFormatDetector.java
> +    // see webp spec https://developers.google.com/speed/webp/docs/riff_container
주석은 의도하신 것일까요??

2022-08-18 07:45 UTC, cndqjacndqja commented on imagestorage/src/test/java/com/woowacourse/imagestorage/strategy/resize/PngImageResizeStrategyTest.java
> +        class byte값과_변경할_width를_받는_경우 {
메서드를 타고 가보니, resize() 안에서 발생할 수 있는 예외가 꽤 있는 것 같아요!
이 부분도 테스트를 해야 하지 않을까요??

2022-08-18 07:45 UTC, cndqjacndqja commented on imagestorage/src/test/java/com/woowacourse/imagestorage/strategy/resize/JpegImageResizeStrategyTest.java
> +
여기도 예외 케이스가 필요할 것 같아요!

2022-08-18 07:45 UTC, cndqjacndqja commented on imagestorage/src/main/java/com/woowacourse/imagestorage/exception/FileResizeException.java
> +}
현재 File과 관련된 Custom Exception이 많이 추가되었는데요!
이것과 관련해서 추상화된 FileCustomException 같은 것을 하는게 어떨까요??
advice에서 예외를 관리하기 복잡할 수도 있을 것 같아서요! (+ 그리고 추상화된 것으로 관리해도 문제가 될 만한 부분이 없을 것 같습니다!)

2022-08-18 07:45 UTC, cndqjacndqja commented on imagestorage/src/main/java/com/woowacourse/imagestorage/application/response/ImageSaveResponse.java
> +    }
요 부분은 `@Getter`를 쓰지 않은 이유가 있을까요??

2022-08-18 09:38 UTC, jinyoungchoi95 commented on imagestorage/src/main/java/com/woowacourse/imagestorage/domain/ImageExtension.java
> +    GIF("gif", MediaType.IMAGE_GIF, new GifImageResizeStrategy(), new Gif2WebpStrategy()),
네 따로 svg에 대한 Writer 구현체가 없고, Jpeg로 구현되어도 크게 문제는 없는 것 같습니다 :)

2022-08-18 09:42 UTC, jinyoungchoi95 commented on imagestorage/src/main/java/com/woowacourse/imagestorage/strategy/convert/handler/Gif2WebpHandler.java
> +        commands.add(target.toAbsolutePath().toString());
여기는 중복에 대해서 의도적이지는 않은데요.
하단의 `convert()`메소드는 pr에 설명을 달아두었지만 바이너리파일을 만들어서 os에게 실행시키도록 명령하는 기능입니다. 현재는 큰 옵션을 사용한다라고 생각을 안하고 있어서 매개변수를 더 받아서 옵션을 두지 않았는데요. `p`, `m`, `lossless`등의 옵션들이 있는데 구현 바이너리인 `cwebp`와 `gif2webp`가 지원하는 옵션이 달라서 결국 커맨드를 만드는 과정이 달라질거라 분리해두었습니다

2022-08-18 09:43 UTC, jinyoungchoi95 commented on imagestorage/src/main/java/com/woowacourse/imagestorage/strategy/convert/Gif2WebpStrategy.java
> +    private static final Gif2WebpHandler DEFAULT = new Gif2WebpHandler();
handler를 공통적으로 사용할거라 static final로 분리해두었습니다

급하게 기능사항 충족을 위해 구현된 내용이어서 component를 사용하거나 싱글톤 형태로 수정될 듯 합니다~

2022-08-18 09:46 UTC, jinyoungchoi95 commented on imagestorage/src/main/java/com/woowacourse/imagestorage/application/ImageService.java
> +                return ImageResponse.of(imageExtension.convertToWebp(resizedImage), new MediaType("image", "webp"));
그..... 스프링이 해주면요....? 스프링이 https://www.rfc-editor.org/rfc/rfc7231#section-3.1.1.1 를 따르고 있어서 해줄지는 모르겠네요ㅋㅋㅋㅋㅋ

상수로는 변경해두었습니다.

2022-08-18 09:47 UTC, jinyoungchoi95 commented on imagestorage/src/main/java/com/woowacourse/imagestorage/strategy/convert/handler/CwebpHandler.java
> +public class CwebpHandler extends WebpHandler {
`cwebp`이라는 바이너리가 conver to webp을 해주는 바이너리라 해당하는 명칭이 주어지는 듯 하네요
반대로 `dewebp`은 decode to webp인듯 합니다~

2022-08-18 09:50 UTC, jinyoungchoi95 commented on imagestorage/src/main/java/com/woowacourse/imagestorage/strategy/convert/handler/Gif2WebpHandler.java
> +    }
`Process process = builder.start();`의 경우 실제로 바이너리 통한 커맨드를 실행하는 부분이구요.

`waitFor`는 로직이 실행되는 동안 기다리는 구간, `process.exitValue()`는 실행 시 나타나는 에러 메시지를 `stdout`파일에 저장해서 디버깅하기 위함입니다

2022-08-18 09:50 UTC, jinyoungchoi95 commented on imagestorage/src/main/java/com/woowacourse/imagestorage/strategy/convert/handler/CwebpHandler.java
> +            process.waitFor(5, TimeUnit.MINUTES);
위에 설명되어있습니다~

2022-08-18 09:51 UTC, jinyoungchoi95 commented on imagestorage/src/main/java/com/woowacourse/imagestorage/strategy/convert/handler/CwebpHandler.java
> +        if (exitStatus != 0) {
```java
private void checkSuccessProcess(final Path stdout, final Process process) throws IOException {
    int exitStatus = process.exitValue();
    if (exitStatus != 0) {
        List<String> error = Files.readAllLines(stdout);
        throw new IOException(error.toString());
    }
}
```

2022-08-18 09:58 UTC, jinyoungchoi95 commented on imagestorage/src/main/java/com/woowacourse/imagestorage/strategy/convert/handler/Gif2WebpHandler.java
> +        Path stdout = Files.createTempFile("stdout", "webp");
위에도 설명되어있는부분인데요 https://github.com/woowacourse-teams/2022-gong-check/pull/523#discussion_r948905789
해당부분은 중복이라기보다는 어쩔수없이 해당 바이너리들의 명령이 다르기때문에 분리가 되어있습니다.
중복이 잡히더라도 넘어가야할듯한데 어떻게 생각하세요?

2022-08-18 09:59 UTC, jinyoungchoi95 commented on imagestorage/src/main/java/com/woowacourse/imagestorage/strategy/convert/handler/WebpHandler.java
> +                    .waitFor(30, TimeUnit.SECONDS);
현재는 해당 파일에 대한 chmod 권한을 풀어주는 부분이고, waitFor는 커맨트를 실행시키는 로직입니다.

둘 다 현재 자바 어플리케이션에서 진행하는 것이 아닌 외부의 os 커맨드에 실행을 요구하고 실행결과를 받는 부분이기때문에 실행이 완료되기까지 wait를 해주어야 합니다

2022-08-18 09:59 UTC, jinyoungchoi95 commented on imagestorage/src/test/java/com/woowacourse/imagestorage/ImageFormatDetector.java
> +    // see webp spec https://developers.google.com/speed/webp/docs/riff_container
넵 참고차 두었습니다 지워둘게요 :)

2022-08-18 10:00 UTC, jinyoungchoi95 commented on imagestorage/src/main/java/com/woowacourse/imagestorage/application/response/ImageSaveResponse.java
> +    }
그렇네요...?

2022-08-18 11:27 UTC, jinyoungchoi95 commented on imagestorage/src/main/java/com/woowacourse/imagestorage/exception/FileResizeException.java
> +}
일단 현재와 같이두고 pr 진행전에 작업되었던 이슈 구체화 pr에 맞게 따로 수정하는 방향으로 가겠습니다 :)

2022-08-18 11:28 UTC, jinyoungchoi95 commented on imagestorage/src/test/java/com/woowacourse/imagestorage/strategy/resize/PngImageResizeStrategyTest.java
> +        class byte값과_변경할_width를_받는_경우 {
외부 라이브러리에 대한 이슈여서 해당 구현체에서 모두 잡아주기보다는 지금과 같이 두는게 좋을 것 같다라는 생각입니다 :)

width의 경우에는 작은 값이 들어오는 경우에 대해서 한번에 처리하기 위해서 vo를 추가해두었습니다~

2022-08-19 03:59 UTC, awesomeo184 approved these changes
LGTM

2022-08-19 03:59 UTC, cndqjacndqja approved these changes

2022-08-19 05:26 UTC, merged