[FE] 랜딩페이지 컴포넌트를 분리해야 한다.
woowacourse-teams/2022-gong-check pull request #569
Opened 2022-09-16 12:18 UTC by intae92

## issue
- resolve #565 

## 코드 설명
- 랜딩페이지에 있던 컴포넌트들을 분리했습니다.

2022-09-16 15:50 UTC, cks3066 commented on frontend/src/components/host/LandingView/FloatingActionButton/index.tsx
> +  const { eventNumber, onClick } = useFloatingActionButton(mainRef);
1. 지금 처럼 props로 mainRef를 넘겨서 RefObject를 사용하기

2. HTML 엘리먼트인 mainRef.current를 넘겨서 사용하기

1번을 선택한 이유가 있을까요?

2022-09-16 15:52 UTC, cks3066 commented on frontend/src/components/host/LandingView/FloatingActionButton/index.tsx
> +  const { eventNumber, onClick } = useFloatingActionButton(mainRef);
useOnContainerScroll 훅을 사용하기 위한 구조인 것으로 파악되는데, 
useOnContainerScroll 훅 로직에서 RefObject가 필요한 이유가 있을지요?

2022-09-16 15:58 UTC, cks3066 commented on frontend/src/types/index.ts
> +};
```suggestion
export type UserImageType = '160w' | '240w' | '320w' | '480w' | { fallback: string };
```

'160w' 같은 값들은 변수가 아닌 상수인데, string 타입이 아닌 상수 자체로써 타입 선언을 해주는게 어떨까요?

2022-09-16 16:02 UTC, cks3066 commented
많은 작업이었을텐데, 너무 고생많으셨습니다. 
props, 인자로 넘기는 refObject에 대한 부가적인 설명과

타입 지정 부분 봐주세요!

FIle Change 에서 보이는 컴포넌트 및 props 타입 지정이 다른 부분들이 있는데, 기존에 쭉 작성하던 컴포넌트 타입 양식인 React.FC<ComponentProps>로 코드 통일성을 지키는게 어떨까요?

2022-09-16 16:03 UTC, cks3066 requested changes
많은 작업이었을텐데, 너무 고생많으셨습니다.
props, 인자로 넘기는 refObject에 대한 부가적인 설명 부탁드릴게요!

FIle Change 에서 보이는 컴포넌트 및 props 타입 지정이 다른 부분들이 있는데, 기존에 쭉 작성하던 컴포넌트 타입 양식인 React.FC로 코드 통일성을 지키는게 어떨까요?

2022-09-16 22:23 UTC, intae92 commented on frontend/src/types/index.ts
> +};
타입을 다음과 같이 사용하고 있습니다. `type ImagePathType = string;`를 추가 했습니다.
좀 더 직관적으로 타입을 선언 했어야 했는데...아쉽게 됐네요

```javascript
// types/index.ts
type ImagePathType = string;

export type UserImageType = {
  '160w': ImagePathType;
  '240w': ImagePathType;
  '320w': ImagePathType;
  '480w': ImagePathType;
  fallback: ImagePathType;
};

// UserViewSection3/index.tsx
import mobileView3_160w from '@/assets/mobileView3-160w.webp';
import mobileView3_240w from '@/assets/mobileView3-240w.webp';
import mobileView3_320w from '@/assets/mobileView3-320w.webp';
import mobileView3_480w from '@/assets/mobileView3-480w.webp';
import mobileView3_fallback from '@/assets/mobileView3-fallback.png';

const mobileView3: UserImageType = {
  '160w': mobileView3_160w,
  '240w': mobileView3_240w,
  '320w': mobileView3_320w,
  '480w': mobileView3_480w,
  fallback: mobileView3_fallback,
};

```

2022-09-16 22:44 UTC, intae92 commented on frontend/src/components/host/LandingView/FloatingActionButton/index.tsx
> +  const { eventNumber, onClick } = useFloatingActionButton(mainRef);
DOM Element를 담기 위한 useRef로 선언한 변수를 props로 전달할 때, 변수의 current 속성만 넘기지 않고 변수 자체를 전달 합니다.
특별한 이유는 없고 단지 코드의 일관성을 유지 하기 위해서 입니다. 어디에서는 elementRef.current로 props를 전달해 element만 사용하고 어디는 elementRef를 전달해서 elemenet.current로 사용하지 않기 위해서입니다.

elemenetRef로 props를 전달 했기 때문에 useOnContainerScroll 로직에서 RefObject를 선언했습니다. 타입을 보고 ReadOnly 속성인것을 알 수 있어 좋은거 같아요.

팀 내에서 컨벤션을 정해지면 해당 컨벤션으로 따를 생각입니다.

2022-09-16 22:46 UTC, intae92 commented
> 많은 작업이었을텐데, 너무 고생많으셨습니다.
props, 인자로 넘기는 refObject에 대한 부가적인 설명 부탁드릴게요!
FIle Change 에서 보이는 컴포넌트 및 props 타입 지정이 다른 부분들이 있는데, 기존에 쭉 작성하던 컴포넌트 타입 양식인 React.FC로 코드 통일성을 지키는게 어떨까요?

코드 리뷰 반영했습니다. 컴포넌트 타입을 까먹었네요 ㅎㅎ..

2022-09-18 14:29 UTC, cks3066 commented on frontend/src/components/host/LandingView/FloatingActionButton/index.tsx
> +  const { eventNumber, onClick } = useFloatingActionButton(mainRef);
제네릭에 HTML 엘리먼트라는 타입이 있어서 엘리먼트를 넘기고있구나라고 타입추론은 가능할 것같은데, 코드만 보고서는 element를 다루는 컴포넌트, 훅인지는 구별이 안될 것같기도합니다.
개인적으로는 element 자체를 넘기는게 어떨까싶기도한데, 큰 문제가 있는 건 아닌것같아서 approve 하겠습니다

2022-09-18 14:41 UTC, cks3066 commented on frontend/src/types/index.ts
> +};
mapped type을 이용하면 조금 더 제한적인 key 값을 부여할 수 있을 것 같아요.

```js
type ImagePathType = '160w' | '240w' | '320w' | '480w' | 'fallback';

type UserImageType = {[K in ImagePathType]: string};

const mobileView1: UserImageType = {
  '160w': mobileView1_160w,
  '240w': mobileView1_240w,
  '320w': mobileView1_320w,
  '480w': mobileView1_480w,
  fallback: mobileView1_fallback,
};
```

2022-09-18 14:42 UTC, cks3066 approved these changes
approve 하겠습니다! 코멘트는 확인 부탁드려요!!

2022-09-19 04:31 UTC, intae92 commented
매트타입 좋은 방법이네요. 다음번에 적용해 보겠습니다. ReadyOnly인 useRef.current를 넘기는것도 좋은거 같아요.

2022-09-19 04:31 UTC, merged