[BE] host profile 조회 api를 구현한다.
woowacourse-teams/2022-gong-check pull request #598
Opened 2022-10-12 01:44 UTC by kimchan123

## issue
- resolve #596 

## 코드 설명
- host에 nickname column을 추가했습니다.
- 이미 가입한 사용자의 nickname은 '닉네임 변경 바람'으로 설정하기로 했습니다.
- 추후 nickname 변경 api를 생성할 예정입니다.

2022-10-12 01:48 UTC, jinyoungchoi95 requested changes
수고하셨습니다~

개행 및 컨벤션 관련 커맨트 남겨두었습니다 :) 확인부탁드려요

2022-10-12 01:48 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/core/presentation/HostController.java
> +
```suggestion
```
불필요한 공백이네요

2022-10-12 01:48 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/core/presentation/HostController.java
> +        final HostProfileResponse response = hostService.findProfile(hostId);
```suggestion
        HostProfileResponse response = hostService.findProfile(hostId);
```
메소드 변수에 final을 달지 않는게 컨벤션이었습니다 :)

2022-10-12 01:48 UTC, jinyoungchoi95 commented on backend/src/test/java/com/woowacourse/gongcheck/core/application/HostServiceTest.java
> +
```suggestion
```

2022-10-12 01:51 UTC, meatsby requested changes

2022-10-12 01:51 UTC, meatsby commented on backend/src/main/java/com/woowacourse/gongcheck/core/domain/host/Host.java
>      private LocalDateTime createdAt;
```suggestion
    @Column(name = "image_url", nullable = false)
    private String imageUrl;

    @Column(name = "nickname", nullable = false)
    private String nickname;
    
    @CreatedDate
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;
```

2022-10-12 01:51 UTC, meatsby commented on backend/src/main/java/com/woowacourse/gongcheck/core/domain/host/Host.java
> +                LocalDateTime createdAt, LocalDateTime updatedAt) {
`final` 이 왜 다 빠졌죠..?!

2022-10-12 01:52 UTC, cndqjacndqja commented on backend/src/main/java/com/woowacourse/gongcheck/core/domain/host/Host.java
> +    private String nickname;
개행이 빠진 것 같아요!

2022-10-12 01:53 UTC, kimchan123 commented on backend/src/main/java/com/woowacourse/gongcheck/core/domain/host/Host.java
>      private LocalDateTime createdAt;
반영했습니다!

2022-10-12 01:54 UTC, cndqjacndqja approved these changes

2022-10-12 02:20 UTC, kimchan123 commented
@jinyoungchoi95 
@meatsby 
리뷰 반영 했습니다!

2022-10-12 03:22 UTC, meatsby approved these changes
LGTM!

2022-10-13 02:25 UTC, jinyoungchoi95 approved these changes

2022-10-13 02:26 UTC, merged