[BE] Host profile 상세정보 변경 api를 구현한다.
woowacourse-teams/2022-gong-check pull request #609
Opened 2022-10-14 01:59 UTC by kimchan123

## issue
- resolve #607  

## 코드 설명
- profile 상세정보 변경 api를 구현했습니다.
- 현재 변경할 field가 nickname 밖에 없어 nickname만 변경하는 상황입니다.

2022-10-14 02:02 UTC, jinyoungchoi95 requested changes
빠르게 잘 구현하셨네요 👍 

한가지 의견남겨두었으니 확인부탁드려요 :)

2022-10-14 03:02 UTC, cndqjacndqja requested changes
수고하셨습니다 :)
테스트 관련 코멘트 하나만 남겼습니다!

2022-10-14 03:09 UTC, kimchan123 commented on backend/src/main/java/com/woowacourse/gongcheck/core/domain/host/Host.java
> +        this.nickname = nickname;
Nickname VO 생성했습니다!

2022-10-14 03:17 UTC, awesomeo184 approved these changes
LGTM! 근데 커버리지가 왜 이렇게 낮게 나왔을까여

2022-10-14 03:18 UTC, kimchan123 commented on backend/src/main/java/com/woowacourse/gongcheck/core/presentation/request/HostProfileChangeRequest.java
> +    private String nickname;
추가했습니다!

2022-10-14 08:20 UTC, jinyoungchoi95 approved these changes

2022-10-16 05:28 UTC, cndqjacndqja approved these changes
수고하셨습니다 ~ :)

2022-10-17 04:54 UTC, meatsby approved these changes
늦리뷰 죄송함다 ㅠ LGTM 이네요!

2022-10-17 04:57 UTC, merged