[BE] 제출하기 API 를 구현한다.
woowacourse-teams/2022-gong-check pull request #61
Opened 2022-07-06 07:07 UTC by meatsby

## issue
- #53 

## 코드 설명

### taskIds 로 컬럼이 allTrue 인지 확인할 방법은 없을까요?
전체 RunningTask 의 is_checked 컬럼이 true 인지 확인하기 위해 RunningTasks 라는 일급컬렉션을 만들어 모두 true 인지 확인하도록 구현했습니다. 개인적으론 조회 시에 컬럼이 모두 true 인지 boolean 으로 받아보고 싶은데 아직 방법을 찾지 못했네영..

### FixtureFactory 에 RunningTaskBuilder 에 taskId 랑 boolean 을 넣는 건 어떨까요?
```java
    public static RunningTask RunningTask_생성(final Long taskId, final boolean isChecked) {
        return RunningTask.builder()
                .taskId(taskId)
                .isChecked(isChecked)
                .createdAt(LocalDateTime.now())
                .build();
    }
```
RunningTask 의 체크 여부를 판단하기 위한 테스트를 만드는 도중 픽스처가 Task 를 받는 것으로 한정되어 있더라구요. 개인적으론 엔티티도 taskId 를 필드로 가지고 있고 체크 여부를 설정할 수 있게끔 위처럼 수정하면 범용적으로 사용할 수 있을 것 같다고 생각했습니다.

### 기존 API 명세에서 제출 요청 시 Author 바디가 없어서 추가했습니다.
```java
POST /api/jobs/{jobId}/complete HTTP/1.1
Authorization : Bearer jwt.token.here
{
  "author": "제출자"
}
```

### 인수테스트 미완성
인수테스트 시나리오를 구성하기 위해선 체크하기 API 가 필요하더라구요. 일단 코드는 추가해두어서 추후에 병합되면 테스트 통과할 것 같습니다.

2022-07-06 07:53 UTC, awesomeo184 requested changes
고생하셨습니다~ 몇가지 코멘트 남겼습니다. 확인 부탁드려요

2022-07-06 08:16 UTC, meatsby commented on backend/src/main/java/com/woowacourse/gongcheck/domain/task/RunningTasks.java
> +    }
오오! `allMatch()` 라는 기능도 있네요! 수정하겠습니다!

2022-07-06 08:41 UTC, meatsby commented on backend/src/main/java/com/woowacourse/gongcheck/application/SubmissionService.java
> +                .build());
좀 더 도메인 관점적인 것 같아요! 가독성도 좋은 것 같구요.
변경했습니다!

2022-07-06 09:08 UTC, meatsby commented on backend/src/test/java/com/woowacourse/gongcheck/application/SubmissionServiceTest.java
> +    }
줄여볼게요!

2022-07-06 09:08 UTC, meatsby commented on backend/src/test/java/com/woowacourse/gongcheck/presentation/SubmissionControllerTest.java
> +                .header("Authorization", "Bearer jwt.token.here")
적용 완료!

2022-07-06 10:22 UTC, kimchan123 requested changes
고생하셨어요!👍

2022-07-06 10:22 UTC, kimchan123 commented on backend/src/main/java/com/woowacourse/gongcheck/domain/job/Job.java
> +
이렇게 되면 Submission -> Job 참조가 있는 상황에서 Job -> Submission 참조가 생겨 순환참조가 될 것 같은데 괜찮을까요??? (진짜 몰라서 물어보는 것..)

2022-07-07 04:40 UTC, jinyoungchoi95 approved these changes

2022-07-07 04:48 UTC, kimchan123 approved these changes
고생하셨어요~! 사소한 컨벤션 하나 남겼습니당

2022-07-07 04:48 UTC, kimchan123 commented on backend/src/test/java/com/woowacourse/gongcheck/application/SubmissionServiceTest.java
> +            submissionService.submitJobCompletion(hostWithTasks.getId(), job.getId(), request);
개행 해주시면 좋을 것 같아요~!

2022-07-07 04:50 UTC, merged