[BE] 진행중인 작업을 조회하는 API를 구현한다.
woowacourse-teams/2022-gong-check pull request #64
Opened 2022-07-06 08:55 UTC by kimchan123

## issue
- #54 

## 코드 설명
### 실행과정

```
1. Host를 찾는다 (host가 존재하지 않으면 예외 발생)
2. Job을 찾는다 (host와 jobid가 일치하지 않으면 예외 발생)
3. Job이 가지고있는 Tasks를 찾는다
4. 해당 Tasks중 RunningTask를 가진 Task가 없으면 예외를 발생시킨다
5. RunningTask를 가진 Task가 존재한다면 진행중인 작업이 있는 것이므로 Tasks로 RunningTasksResponse를 만들어 반환합니다.
```

### 문제 상황
현재 RunningTask들을 조회하기 위해선 TaskId를 통해 조회해야 합니다.
이 행위가 부자연스러울 뿐더러 Task와 RunningTask가 거의 비슷하기 때문에 Task로 RunningTask를 조회하고 다시 RunningTask 부터 객체탐색을 시작하는 것이 비효율적으로 느껴집니다. 어차피 Task -> RunningTask 참조가 생겨도 조회만 할 것 이기 때문에 Task에 RunningTask 필드를 추가하였습니다.

### 코드 변경 사항
1. #46 에서 삭제한 @MapsId를 이용한 Task 필드를 다시 복구하였습니다.
```java
@MapsId("taskId")
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "task_id", nullable = false)
    private Task task;
```
2. Task에도 RunningTask 연관관계 매핑을 추가하였습니다. 이와 동시에 N+1 쿼리 문제를 해결하기 위해 @EntityGraph를 사용했습니다.
```java
public class Task {

    @OneToOne(mappedBy = "task", fetch = FetchType.LAZY)
    private RunningTask runningTask;
}

public interface TaskRepository extends JpaRepository<Task, Long> {

    @EntityGraph(attributePaths = {"runningTask"}, type = EntityGraphType.FETCH)
    List<Task> findAllBySectionJob(final Job job);
}

2022-07-06 09:06 UTC, cndqjacndqja approved these changes
생각보다 구현해야 할 것들이 많아서 놀랬습니다 고생하셨네요😂
몇 가지 코멘트 남겼습니다~!
수고하셨습니다 :)

2022-07-06 09:08 UTC, awesomeo184 approved these changes

2022-07-06 10:30 UTC, meatsby approved these changes
수고하셨습니다!

2022-07-06 10:30 UTC, meatsby commented on backend/src/main/java/com/woowacourse/gongcheck/application/response/RunningTasksWithSectionResponse.java
> +    public RunningTasksWithSectionResponse(final Long id, final String name,
private 으로 막아야하지 않을까요?

2022-07-06 10:30 UTC, meatsby commented on backend/src/main/java/com/woowacourse/gongcheck/domain/task/RunningTask.java
> +    public RunningTask(Long taskId, Task task, boolean isChecked, LocalDateTime createdAt) {
final 이 필요할 것 같아요!

2022-07-06 10:47 UTC, kimchan123 commented on backend/src/main/java/com/woowacourse/gongcheck/domain/task/RunningTask.java
>          this.taskId = taskId;
빠져있는 곳이 많아서 나중에 일괄적으로 처리할 것 같아요!

2022-07-06 10:50 UTC, kimchan123 commented on backend/src/test/java/com/woowacourse/gongcheck/application/TaskServiceTest.java
> +            entityManager.clear();
clear()가 필요해요 ㅠㅠ

2022-07-06 11:00 UTC, kimchan123 commented on backend/src/test/java/com/woowacourse/gongcheck/application/TaskServiceTest.java
> +            taskRepository.saveAll(List.of(task1, task2));
적용해봤습니다!

2022-07-06 11:04 UTC, kimchan123 commented on backend/src/main/java/com/woowacourse/gongcheck/domain/task/RunningTask.java
> +    public RunningTask(Long taskId, Task task, boolean isChecked, LocalDateTime createdAt) {
안된 부분이 많아서 일괄적으로 처리하기로 했어요!

2022-07-06 11:13 UTC, jinyoungchoi95 requested changes
고생하셨습니다~ 
코맨트 확인 부탁드려요 :)

2022-07-06 11:13 UTC, jinyoungchoi95 commented on backend/src/main/java/com/woowacourse/gongcheck/domain/task/TaskRepository.java
> +    @EntityGraph(attributePaths = {"runningTask"}, type = EntityGraphType.FETCH)
fetch join 👍

2022-07-06 11:17 UTC, kimchan123 commented on backend/src/test/java/com/woowacourse/gongcheck/application/TaskServiceTest.java
> +    @PersistenceContext
EntityManager를 사용한다는 것을 명시적으로 표현하기 위해 사용했는데 위의 컨벤션과 동일하게 맞추는 것이 좋아보여 변경했습니다~!

2022-07-06 11:18 UTC, kimchan123 commented on backend/src/test/java/com/woowacourse/gongcheck/documentation/TaskDocumentation.java
> +        Task task2 = RunningTask로_Task_생성(runningTask2, section2, "의자 청소");
지저분 하긴 하네요...ㅜ

2022-07-07 01:51 UTC, kimchan123 commented on backend/src/main/java/com/woowacourse/gongcheck/application/response/RunningTaskResponse.java
> +    private Boolean checked;
Boolean -> boolean으로 변경하였습니다!

2022-07-07 01:52 UTC, merged