[BE] 웹소켓 API 인수테스트 및 문서 작성, 미사용 API 및 문서 제거
woowacourse-teams/2022-gong-check pull request #657
Opened 2022-10-26 08:11 UTC by awesomeo184

## issue
- resolve #655 
- resolve #656 

## 코드 설명
- `WebSocketStompClient`를 이용한 웹 소켓 API 인수테스트를 작성하였습니다.
- `SubmitController`의 이름을 `SubmissionController`로 변경하고, 기존에 SubmissionController에 있던 호스트용 Submission 조회 API를 TaskController로 이동하였습니다. 웹 소켓 통신을 위한 Controller를 따로 분리하기 위한 목적입니다.
- SSE를 사용할 때 쓰던 API와 문서를 모두 제거하였습니다.

2022-10-26 10:25 UTC, cndqjacndqja requested changes
어썸오 처음 적용해 보셨을텐데 수고하셨습니다 :)
관련해서 궁금한 점 코멘트로 남겼습니다!

2022-10-26 10:25 UTC, cndqjacndqja commented on backend/src/test/java/com/woowacourse/gongcheck/acceptance/TaskAcceptanceTest.java
> +            System.out.println(payload);
👀?!

2022-10-26 10:25 UTC, cndqjacndqja commented on backend/src/test/java/com/woowacourse/gongcheck/acceptance/TaskAcceptanceTest.java
> +        private final BlockingQueue<T> responses;
어떤 역할을 해주는 클래스인가요??
꼭 BlockingQueue를 사용해야 하나요??

2022-10-26 10:25 UTC, cndqjacndqja commented on backend/src/test/java/com/woowacourse/gongcheck/acceptance/TaskAcceptanceTest.java
> +    void RunningTask의_체크상태를_변경한다() throws Exception {
예외 검증은 안해도 될까요??

2022-11-10 07:21 UTC, awesomeo184 commented on backend/src/test/java/com/woowacourse/gongcheck/acceptance/TaskAcceptanceTest.java
> +        private final BlockingQueue<T> responses;
웹소켓 서버 응답은 다른 쓰레드에서 동작하기 때문에 BlockingQueue를 사용하지 않으면 메시지를 주고 받고 나서 데이터가 사라지게 됩니다.

2022-11-10 07:25 UTC, meatsby approved these changes
LGTM

2022-11-10 07:26 UTC, cndqjacndqja approved these changes

2022-11-14 05:47 UTC, merged